/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   17/03/2016 17:12:09
*/

Ext.define('MyApp.model.GestionarSaldo.GuiaPesoQueryModel', {
    extend: 'Ext.data.Model',
    fields: [		
    	     {name: 'id_guia_peso', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_guia', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_tipo_peso', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'descrip_tipo_peso', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'num_jabas', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'num_aves', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'peso_obtenido', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_estado', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'descrip_estado', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_registro', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_modificacion', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_usuario_reg', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_usuario_mod', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ],
   idProperty:'id_guia_peso'
});