/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 20:07:02
*/

Ext.define('MyApp.controller.GestionarAplicacion.MainController', {
    extend: 'Ext.app.Controller',

    stores: ['GestionarAplicacion.MainStore'],

    models: ['GestionarAplicacion.MainModel'],

    views: ['GestionarAplicacion.Edit', 'GestionarAplicacion.List'],

    refs: [
    	{
            ref: 'GestionarAplicacionPanel',
            selector: 'panel'
        },
        {
            ref: 'GestionarAplicacionList',
            selector: 'GestionarAplicacionList'
        }
    ],

    init: function() {
    
        Ext.getStore('GestionarAplicacion.MainStore').addListener('beforeload',this.setExtraParams,this);
        
        this.control({
            'GestionarAplicacionList dataview': {
                itemdblclick: this.editRecord
            },
            'GestionarAplicacionList button[action=add]': {
            	click: this.editRecord
            },
            'GestionarAplicacionList button[action=delete]': {
                click: this.deleteRecord
            },
            'GestionarAplicacionEdit button[action=save]': {
                click: this.updateRecord
            },
            'GestionarAplicacionList button[action=filter]': {
                click: this.refreshGrid
            },
            'GestionarAplicacionList button[action=clearFilter]': {
                click: this.resetForm
            },
            'GestionarAplicacionList combobox': {
                change: this.refreshGrid
            },
            'GestionarAplicacionList textfield': {
            	specialkey: this.onKeyEnter
            }
        });
    },

    editRecord: function(grid, record) {
        var edit = Ext.create('MyApp.view.GestionarAplicacion.Edit').show();
        var form = edit.down('form');
        if(record.data){
        	edit.down('form').loadRecord(record);
        	edit.setTitle('Editar');
        	
        	var subModel_PerfilAplicacionSubCrud = Ext.getCmp('subModel_PerfilAplicacionSubCrud');
        	var id_aplicacion = form.getForm().findField('id_aplicacion');
        	
			subModel_PerfilAplicacionSubCrud.store.reload({params: {id_aplicacion: id_aplicacion.getValue(), start:0, limit:10}});
			
        }else{
        	edit.setTitle('Agregar');
        	var subModel_PerfilAplicacionSubCrud = Ext.getCmp('subModel_PerfilAplicacionSubCrud');
			subModel_PerfilAplicacionSubCrud.store.reload({params: {id_aplicacion: -1, start:0, limit:10}});
        }
    },
    
    updateRecord: function(button) {
    	
        var win = button.up('window');
        var form = win.down('form');
        var record = form.getRecord();
        var values = form.getValues();
        var store = Ext.getStore('GestionarAplicacion.MainStore');
        
        if (form.isValid()) {
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de GRABAR el registro?',function (btn) {
	            
	            if (btn == 'yes') {
	        		if (values.id_aplicacion > 0){
	        			values.tokenField = 'update';
	        			record.set(values);
	        		} else{
	        			record = Ext.create('MyApp.model.GestionarAplicacion.MainModel');
	        			values.tokenField = 'insert';
	        			record.set(values);
	        			store.add(record);
	        		}
	                
	        		store.sync({
	        	        success: function (batch, eOpts) {
				        	store.load();
				        	win.close();
	        	        },
	        	        failure: function (batch, eOpts) {
							store.rejectChanges();
	        	        }
	        	    });
	            }
	        });
		}

    },
    
    deleteRecord: function(button) {
    	
    	var grid = this.getGestionarAplicacionList();
    	var record = grid.getSelectionModel().getSelection(); 
    	var store = Ext.getStore('GestionarAplicacion.MainStore');
    	
    	if(record.length > 0){
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de ELIMINAR el registro?',function (btn) {
	                if (btn == 'yes') {
	             	   store.remove(record);
						store.sync({
					        success: function (batch, eOpts) {
					        	store.load();
					        }
					    });
	                }
	        });
    	}

    },
    refreshGrid: function() {
    	var store = Ext.getStore('GestionarAplicacion.MainStore');
    	store.load({start:0});
    },
    resetForm: function() {
    	var store = Ext.getStore('GestionarAplicacion.MainStore');
        var form = Ext.getCmp('form_filter_GestionarAplicacion');
        form.reset();
    	store.load({start:0});
    },
    onKeyEnter: function(field, event, options) {
        if (event.getKey() == event.ENTER) {
        	var store = Ext.getStore('GestionarAplicacion.MainStore');
        	store.load({start:0});
        }
    },
    setExtraParams: function(field, event, options) {
    	var store = Ext.getStore('GestionarAplicacion.MainStore');
        var form = Ext.getCmp('form_filter_GestionarAplicacion');
        var values = form.getValues();
    	store.getProxy().extraParams = values;
    }
    
});