/*
* Copyright «©» 2017, KAPCOM SOFTWARE S.R.L. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.4.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.4.0] by JRaffo 
*/

/**
* The ProductQueryMapper interface content the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   05/09/2017 12:15:39
*/

package pe.com.kapcom.tambos.lima.common.model.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.kapcom.tambos.lima.common.model.bean.ProductQuery;
import pe.com.kapcom.tambos.lima.common.model.bean.ProductQueryCriteria;

public interface ProductQueryMapper {
   List<ProductQuery> getListQueryByCriteria(ProductQueryCriteria criteria);
   List<ProductQuery> getListQueryByMap(Map<String, Object> paramMap);
   List<ProductQuery> getListQueryPaginationByCriteria(ProductQueryCriteria criteria, RowBounds rowBounds);
   List<ProductQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds);
   int getCountRowsByCriteria(ProductQueryCriteria criteria);
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
