package sernanp.rrhh.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Areaorganica generated by hbm2java
 */
public class Areaorganica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idarea;
	private Sede sede;
	private Tipo tipoareaorganica;
	private String codarea;
	private String desarea;
	private String telefonoarea;
	private String direccionarea;
	private List<Usuario> usuarios = new ArrayList<Usuario>();

	
	public Areaorganica(int idarea){
		this();
		this.idarea=idarea;
	}
	
	
	public Areaorganica() {
		sede=new Sede();
		tipoareaorganica=new Tipo();
	}

		public int getIdarea() {
		return this.idarea;
	}

	public void setIdarea(int idarea) {
		this.idarea = idarea;
	}

	
	public Tipo getTipoareaorganica() {
		return tipoareaorganica;
	}


	public void setTipoareaorganica(Tipo tipoareaorganica) {
		this.tipoareaorganica = tipoareaorganica;
	}


	public String getTelefonoarea() {
		return telefonoarea;
	}


	public void setTelefonoarea(String telefonoarea) {
		this.telefonoarea = telefonoarea;
	}


	public String getDireccionarea() {
		return direccionarea;
	}


	public void setDireccionarea(String direccionarea) {
		this.direccionarea = direccionarea;
	}


	public Sede getSede() {
		return sede;
	}
	public void setSede(Sede sede) {
		this.sede = sede;
	}
	public String getCodarea() {
		return this.codarea;
	}

	public void setCodarea(String codarea) {
		this.codarea = codarea;
	}

	public String getDesarea() {
		return this.desarea;
	}

	public void setDesarea(String desarea) {
		this.desarea = desarea;
	}

	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
