/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   14/09/2016 05:45:45
*/

Ext.define('MyApp.model.GestionarDocFactura.MainModel', {
    extend: 'Ext.data.Model',
    fields: [
    	     {name: 'id_documento_venta', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_tipo_documento_venta', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_emision', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'anio_emision', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'mes_emision', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'dia_emision', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_cancelado', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'serie_docu_venta', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'num_docu_venta', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'serie_num_doc', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_cliente', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'nombres_cliente', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'direccion_cliente', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_tipo_docu_cliente', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'descrip_tipo_docu_cliente', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'num_docu_cliente', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_guia_remision', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'num_guia_remision', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'sub_total_venta', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'valor_igv_venta', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'importe_total', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'flag_percepcion', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'descrip_flag_percepcion', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'percentage_percepcion', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'monto_percepcion', type: 'float', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_estado', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'descrip_estado', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_registro', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'fecha_modificacion', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_usuario_reg', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'id_usuario_mod', type: 'integer', useNull: true, defaultValue:null, allowNull:true}
            ,{name: 'tokenField', type: 'string', useNull: true, defaultValue:null, allowNull:true}
            ],
   idProperty:'id_documento_venta'
});
