/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   05/03/2016 15:14:59
*/

package pe.com.acme.inavi.business.service;

import java.util.List;

import pe.com.acme.query.mybatis.model.GuiaQuery;
import pe.com.acme.query.mybatis.model.GuiaQueryCriteria;
import pe.com.acme.util.IMybatisRepositoryHelper;

public interface GestionarGuiaService extends IMybatisRepositoryHelper {
    Integer create(GuiaQuery model) throws Exception;
    void update(GuiaQuery model) throws Exception;
    void destroy(GuiaQuery model) throws Exception;
    List<GuiaQuery> list(GuiaQueryCriteria criteria) throws Exception;
    int countRecords(GuiaQueryCriteria criteria) throws Exception;
    void grabarCambioPrecio(String fecha_jornada, Double valor) throws Exception;
}