/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   25/07/2016 19:41:32
*/

Ext.define('MyApp.view.MttoCuentaPorCobrar.Edit', {
    extend: 'Ext.window.Window',
    alias : 'widget.MttoCuentaPorCobrarEdit',

    requires: ['Ext.form.Panel'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: '45%',

    iconCls:'icon-pencil',

    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                items: [
							{
				                xtype: 'form',
				                id: 'form_crud_MttoCuentaPorCobrar',
				                padding: '5 5 0 5',
				                border: false,
				                style: 'background-color: #fff;',
				                title: 'Info Cuenta',
//				                glyph:'xf022@FontAwesome',
				                
				                fieldDefaults: {
					    			anchor: '100%',
				                    labelAlign: 'left',
				                    allowBlank: false,
				                    combineErrors: true,
				                    msgTarget: 'qtip',
                    				labelWidth: 125
			                	},

		                		items: [
											{
											    allowBlank : true,
											    xtype : 'textfield',
											    hidden : true,
											    editable : true,
											    fieldLabel : 'id_cuenta_x_cobrar',
											    name : 'id_cuenta_x_cobrar',
											    disabled : false,
											    readOnly : false
											},
											{
												readOnly : false,
												allowBlank : true,
												store : {
													fields: ['id_persona','nombres'],
													proxy: {
														type: 'ajax',
														url: '/InaviWSRestApp/api/common/clientes',
														reader: {
															type: 'json',
															rootProperty: 'list'
														}
													},
													pageSize:10,
													autoLoad: false
												},
												queryMode : 'remote',
												displayField : 'nombres',
												hidden : false,
												xtype : 'combobox',
												// configure paging as we have ~23000 cities
												pageSize:10,
												// number of characters to type to initiate the search
												minChars:2,
												listConfig: {
													loadingText: 'Buscando...',
													emptyText: 'No se encontraron clientes.'
												},
												name : 'id_cliente',
												valueField : 'id_persona',
												emptyText : 'Ingrese nombres o apellidos.',
												fieldLabel : 'Cliente',
												disabled : false,
												editable : true
											}
											,{
											    allowBlank : true,
											    xtype : 'textareafield',
											    hidden : false,
											    editable : true,
											    fieldLabel : 'Glosa',
											    name : 'descrip_glosa',
											    disabled : false,
											    readOnly : false
											},
											{

												readOnly : false,
												allowBlank : false,
												hidden : false,
												xtype : 'datefield',
												name : 'fecha_cuenta',
												fieldLabel : 'Fecha de Cuenta',
												disabled : false,
												editable : true
											}
											,{
											    xtype : 'textfield',
												hidden : false,
												vtype : 'soloNumeroDecimales',
												editable : true,
												fieldLabel : 'Monto',
												name : 'monto_deuda',
												disabled : false,
												readOnly : false
											}
											,{
											    readOnly : false,
											    allowBlank : false,
											    store : {
											    	fields: ['valor_item','descrip_item'],
											    	proxy: {
											    		type: 'ajax',
											    		url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=estado_guia_venta',
											    		reader: {
											    			type: 'json',
											    			rootProperty: 'list'
											    		}
											    	},
											    	autoLoad: true
											    },
											    queryMode : 'local',
											    displayField : 'descrip_item',
											    hidden : false,
											    xtype : 'combobox',
											    name : 'id_estado',
											    valueField : 'valor_item',
											    emptyText : '-- Seleccione Opción --',
											    fieldLabel : 'Estado',
											    disabled : false,
											    editable : false,
											    flex:1
											}
											,{
											    allowBlank : true,
											    xtype : 'textfield',
											    hidden : true,
											    fieldLabel : 'tokenField',
											    name : 'tokenField'
											}
										]
							}
							

							,{
					    		title: 'Amortizaciones',
//					    		glyph:'xf022@FontAwesome',
					    		items: [{id:'subModel_CuentaAmortizacionQuery', xtype:'CuentaAmortizacionQueryList'}]
							}

                ]
            }
        ];
        
        this.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            //id:'buttons',
            ui: 'footer',
            items: ['->', {
            	iconCls:'icon-disk_black',
                itemId: 'save',
                text: 'Grabar',
                action: 'save'
            },{
            	iconCls:'icon-cross',
                text: 'Cancelar',
                scope: this,
                handler: this.close
            }]
        }];

        this.callParent(arguments);      
    }
});
