/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   25/02/2016 20:09:25
*/

Ext.define('MyApp.view.GestionarCatalogo.Filter', {

    extend: 'Ext.form.Panel',
    alias: 'widget.GestionarCatalogoFilter',
    requires: ['Ext.form.Panel'],
    
    id:'form_filter_GestionarCatalogo',
	layout: {
        type: 'vbox'
    },
    fieldDefaults: {
        labelAlign: 'top',
        margin: "0 5 5 5"
    },
                                
    initComponent: function() {
    
    	var form = this;
    
        this.items = [
                {
                	xtype: 'container',
                	layout: {
                		type: 'hbox',
                		align: 'stretch'
                	},
                	items: [
							{
								hidden : false,
								xtype : 'textfield',
								name : 'id_catalogo',
								fieldLabel : 'Id Catalogo',
								disabled : false,
								editable : true
							}
							,{
								hidden : false,
								xtype : 'textfield',
								name : 'nombre_catalogo',
								fieldLabel : 'Nombre',
								disabled : false,
								editable : true
							}
							,{
								hidden : false,
								xtype : 'textfield',
								name : 'id_estado',
								fieldLabel : 'id_estado',
								disabled : false,
								editable : true
							}
						]
					}
        ];

        this.callParent(arguments);
    }
});