/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The NotaCreditoQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   23/08/2016 21:58:57
*/

package pe.com.acme.invoiceelec.model.mybatis.query.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.invoiceelec.model.mybatis.query.dto.NotaCreditoQuery;
import pe.com.acme.invoiceelec.model.mybatis.query.dto.NotaCreditoQueryCriteria;

public interface NotaCreditoQueryMapper { 
   List<NotaCreditoQuery> getListQueryByCriteria(NotaCreditoQueryCriteria criteria);
   List<NotaCreditoQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<NotaCreditoQuery> getListQueryPaginationByCriteria(NotaCreditoQueryCriteria criteria, RowBounds rowBounds); 
   List<NotaCreditoQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(NotaCreditoQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
