/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   13/03/2016 16:05:57
*/

Ext.define('MyApp.view.GestionarGuiaCompra.Edit', {
    extend: 'Ext.window.Window',
    alias : 'widget.GestionarGuiaCompraEdit',

    requires: ['Ext.form.Panel','MyApp.util.InaviUtil'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: '45%',

    iconCls:'icon-pencil',
    
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                items: [
							{
				                xtype: 'form',
				                id: 'form_crud_GestionarGuiaCompra',
				                padding: '5 5 0 5',
				                border: false,
				                style: 'background-color: #fff;',
				                title: 'Guia de Compra',
//				                iconCls:'fa fa-list-alt',
				                
				                fieldDefaults: {
					    			anchor: '100%',
				                    labelAlign: 'top',
				                    allowBlank: false,
				                    combineErrors: true,
				                    msgTarget: 'qtip',
                    				labelWidth: 125,
                    				margin: "0 5 5 5"
			                	},
			                	
		                		items: [

											{
											    readOnly : false,
											    allowBlank : true,
											    hidden : true,
											    xtype : 'textfield',
											    name : 'id_guia',
											    fieldLabel : 'Id',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    allowBlank : true,
											    hidden : true,
											    xtype : 'numberfield',
											    name : 'num_anio',
											    fieldLabel : 'Año',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    allowBlank : true,
											    hidden : true,
											    xtype : 'numberfield',
											    name : 'num_mes',
											    fieldLabel : 'Mes',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    allowBlank : true,
											    hidden : true,
											    xtype : 'numberfield',
											    name : 'num_dia',
											    fieldLabel : 'Dia',
											    disabled : false,
											    editable : true
											},
											{
												xtype: 'container',
												layout: {
													type: 'hbox'
												},
												items: [
												        
															{
															    readOnly : false,
															    allowBlank : false,
															    store : {
															    	fields: ['valor_item','descrip_item'],
															    	proxy: {
															    		type: 'ajax',
															    		url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=tipo_guia',
															    		reader: {
															    			type: 'json',
															    			rootProperty: 'list'
															    		}
															    	},
															    	autoLoad: true
															    },
															    queryMode : 'local',
															    displayField : 'descrip_item',
															    hidden : false,
															    xtype : 'combobox',
															    name : 'id_tipo_guia',
															    valueField : 'valor_item',
															    emptyText : '-- Seleccione Opción --',
															    fieldLabel : 'Tipo Guia',
															    disabled : false,
															    editable : false,
															    listeners: {
															        'change': function(field, newValue, oldValue) {
															        	
															        	var form = Ext.getCmp('form_crud_GestionarGuiaCompra');
															    		var id_guia_referencia = form.getForm().findField('id_guia_referencia');
															    		
															    		//Bruto
															    		if(newValue == 1){
															    			id_guia_referencia.setHidden(true);
															    			id_guia_referencia.allowBlank = true;
															    		}
															    		
															    		//Tara
															    		if(newValue == 2){
															    			id_guia_referencia.setHidden(false);
															    			id_guia_referencia.allowBlank = false;
															    		}
															    		
															        }
															    }
															},
															{
															    readOnly : false,
															    allowBlank : true,
															    hidden : true,
															    xtype : 'textfield',
															    name : 'id_guia_referencia',
															    fieldLabel : 'Nro Guia Referencia',
															    disabled : false,
															    editable : true
															}
												        
												        ]
											},
											{
												xtype: 'container',
												layout: {
													type: 'hbox'
												},
												items: [
												        
															
															{
															    readOnly : false,
															    allowBlank : false,
															    hidden : false,
															    xtype : 'datefield',
															    name : 'fecha_jornada',
															    fieldLabel : 'Fecha de Trabajo',
															    disabled : false,
															    editable : false,
															    flex:1
															}
															,{
															    readOnly : false,
															    allowBlank : false,
															    store : {
															    	fields: ['valor_item','descrip_item'],
															    	proxy: {
															    		type: 'ajax',
															    		url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=tipo_producto',
															    		reader: {
															    			type: 'json',
															    			rootProperty: 'list'
															    		}
															    	},
															    	autoLoad: true
															    },
															    queryMode : 'local',
															    displayField : 'descrip_item',
															    hidden : false,
															    xtype : 'combobox',
															    name : 'id_tipo_producto',
															    valueField : 'valor_item',
															    emptyText : '-- Seleccione Opción --',
															    fieldLabel : 'Tipo Producto',
															    disabled : false,
															    editable : false,
															    flex:1
															}
															,{
															    readOnly : false,
															    allowBlank : false,
															    store : {
															    	fields: ['valor_item','descrip_item'],
															    	proxy: {
															    		type: 'ajax',
															    		url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=estado_generico',
															    		reader: {
															    			type: 'json',
															    			rootProperty: 'list'
															    		}
															    	},
															    	autoLoad: true
															    },
															    queryMode : 'local',
															    displayField : 'descrip_item',
															    hidden : false,
															    xtype : 'combobox',
															    name : 'id_estado',
															    valueField : 'valor_item',
															    emptyText : '-- Seleccione Opción --',
															    fieldLabel : 'Estado',
															    disabled : false,
															    editable : false,
															    flex:1
															}
												        
												      ]
												
											},
											
											{
												xtype: 'container',
												layout: {
													type: 'hbox'
												},
												items: [
															{
															    readOnly : false,
															    allowBlank : false,
															    store : {
															    	fields: ['id_proveedor','nombre_proveedor'],
															    	proxy: {
															    		type: 'ajax',
															    		url: '/InaviWSRestApp/api/common/proveedores',
															    		reader: {
															    			type: 'json',
															    			rootProperty: 'list'
															    		}
															    	},
															    	autoLoad: true
															    },
															    queryMode : 'local',
															    displayField : 'nombre_proveedor',
															    hidden : false,
															    xtype : 'combobox',
															    name : 'id_proveedor',
															    valueField : 'id_proveedor',
															    emptyText : '-- Seleccione Opción --',
															    fieldLabel : 'Proveedor',
															    disabled : false,
															    editable : false,
															    flex:1
															}
												        ]
												
											},

											{
												xtype: 'container',
												layout: {
													type: 'hbox'
												},
												items: [
															{
															    readOnly : false,
															    allowBlank : true,
															    hidden : false,
															    xtype : 'textfield',
															    name : 'precio_aplicado',
															    vtype : 'soloNumeroDecimales',
															    fieldLabel : 'Precio',
															    disabled : false,
															    editable : true
															}
															,{
															    readOnly : true,
															    allowBlank : true,
															    hidden : false,
															    xtype : 'textfield',
															    name : 'total_importe',
															    fieldLabel : 'Total Importe',
															    disabled : false,
															    editable : false,
																listeners: {
																	 'change': function(f, newValue, oldValue){

																		 total = MyApp.util.InaviUtil.formatMoney(f.getValue(),'S/ ');
																		 if(oldValue == ''){
																			 f.setValue(total);
																		 }
																		 
																	  }
																}
															}
												        ]
												
											}
											
											,{
											    allowBlank : true,
											    hidden : true,
											    xtype : 'textfield',
											    name : 'tokenField',
											    fieldLabel : 'tokenField'
											}
										]
							}
							

							,{
					    		title: 'Pesos',
//					    		iconCls:'fa fa-list-alt',
					    		items: [{id:'subModel_GuiaPesoQuery', xtype:'GuiaPesoCompraQueryList'}]
							}

                ]
            }
        ];
        
        this.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            //id:'buttons',
            ui: 'footer',
            items: ['->', {
            	iconCls:'icon-disk_black',
                itemId: 'save',
                text: 'Grabar',
                action: 'save'
            },{
            	iconCls:'icon-cross',
                text: 'Cancelar',
                scope: this,
                handler: this.close
            }]
        }];

        this.callParent(arguments);      
    }
});
