/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   13/03/2016 16:05:57
*/

Ext.define('MyApp.view.GestionarGuiaCompra.List' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.GestionarGuiaCompraList',
    
    requires: ['MyApp.view.GestionarGuiaCompra.Filter','MyApp.util.InaviUtil'],

    iconCls:'icon-application_form',

    title : 'Gestionar Guias de Compras',
    store: 'GestionarGuiaCompra.MainStore',

    columns: [
		{
	    	header: "Id",
			flex:20 / 100,
			dataIndex: 'id_guia',
			hidden:false,
			sortable:true
		}
		,{
			header: "Tipo",
			flex:115 / 100,
			dataIndex: 'descrip_tipo_guia',
			hidden:false,
			sortable:true
		}
		,{
			header: "Jornada",
			flex:115 / 100,
			dataIndex: 'fecha_jornada',
			hidden:false,
			sortable:true
		}
		,{
			header: "Tipo Producto",
			flex:140 / 100,
			dataIndex: 'descrip_tipo_producto',
			hidden:false,
			sortable:true
		}
		,{
			header: "Proveedor",
			flex:250 / 100,
			dataIndex: 'nombre_proveedor',
			hidden:false,
			sortable:true
		}
		, {
            text: 'Total',
            columns: [
	            {
	                text     : 'Bruto',
	                width    : 75,
	                sortable : true,
	                dataIndex: 'total_peso_bruto'
	            }, 
	            {
	                text     : 'Tara',
	                width    : 75,
	                sortable : true,
	                dataIndex: 'total_peso_tara'
	            }, 
	            {
	                text     : 'Devoluciones',
	                width    : 110,
	                sortable : true,
	                dataIndex: 'total_peso_devolucion'
	            }, 
	            {
	                text     : 'Neto',
	                width    : 75,
	                sortable : true,
	                dataIndex: 'total_peso_neto'
	            }
            ]
        }

		,{
			header: "Precio",
			flex:115 / 100,
			dataIndex: 'precio_aplicado',
			hidden:false,
			sortable:true, 
			renderer:function(value) {
				return MyApp.util.InaviUtil.formatMoney(value,'S/ ');
			}
		}
		,{
			header: "Importe Total",
			flex:125 / 100,
			dataIndex: 'total_importe',
			hidden:false,
			sortable:true, 
			renderer:function(value) {
				return MyApp.util.InaviUtil.formatMoney(value,'S/ ');
			}
		}
		,{
			header: "Estado",
			flex:115 / 100,
			dataIndex: 'descrip_estado',
			hidden:false,
			sortable:true
		}
		,{
			header: "F. Registro",
			flex:115 / 100,
			dataIndex: 'fecha_registro',
			hidden:false,
			sortable:true
		}
	],
	
	initComponent: function() {
		
		this.dockedItems = [
		     {
		          xtype: 'GestionarGuiaCompraFilter'
		     },
			 {
	            xtype: 'toolbar',
	            items: [
				            {
				            	iconCls:'icon-find',
				                text: 'Filtrar',
				                action: 'filter'
				            },
				            '-',
				            {
				            	iconCls:'icon-erase',
				                text: 'Limpiar',
				                action: 'clearFilter'
				            },
				            '-',
				            {
				            	iconCls:'icon-add',
				                text: 'Agregar',
				                action: 'add'
				            },
				            '-',
				            {
				            	iconCls:'icon-delete',
				                text: 'Eliminar',
				                action: 'delete'
				            }
			           ]
	        },
	        {
	            xtype: 'pagingtoolbar',
	            dock:'top',
	            store: 'GestionarGuiaCompra.MainStore',
	            displayInfo: true
	        }
        ];
		
		this.callParent(arguments);
        this.on('render', this.loadStore, this);
	},
    loadStore: function() {
        this.getStore().load();
    }
});
