/*
* Copyright «©» 2017, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The CustomerMailQueryCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   06/02/2017 22:14:49
*/

package pe.kapcom.iemail.repository.dto; 

public class CustomerMailQueryCriteria implements java.io.Serializable  {

	private static final long serialVersionUID = 1L;

} 