/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The CharacterQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   30/03/2016 03:20:10
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class CharacterQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private String AccountID; 
	private String Name; 
	private Integer Resets; 
	private Integer cLevel; 
	private Integer LevelUpPoint; 
	private Integer clazz; 
	private String descrip_clazz; 
	private Integer Strength; 
	private Integer Dexterity; 
	private Integer Vitality; 
	private Integer Energy; 
	private Integer Money; 


	public String getAccountID() { 
	  return AccountID; 
	} 
	public void setAccountID(String AccountID) { 
	  this.AccountID = AccountID; 
	} 
	public String getName() { 
	  return Name; 
	} 
	public void setName(String Name) { 
	  this.Name = Name; 
	} 
	public Integer getResets() { 
	  return Resets; 
	} 
	public void setResets(Integer Resets) { 
	  this.Resets = Resets; 
	} 
	public Integer getCLevel() { 
	  return cLevel; 
	} 
	public void setCLevel(Integer cLevel) { 
	  this.cLevel = cLevel; 
	} 
	public Integer getLevelUpPoint() { 
	  return LevelUpPoint; 
	} 
	public void setLevelUpPoint(Integer LevelUpPoint) { 
	  this.LevelUpPoint = LevelUpPoint; 
	} 
	public Integer getClazz() { 
	  return clazz; 
	} 
	public void setClazz(Integer clazz) { 
	  this.clazz = clazz; 
	} 
	public String getDescrip_clazz() { 
	  return descrip_clazz; 
	} 
	public void setDescrip_clazz(String descrip_clazz) { 
	  this.descrip_clazz = descrip_clazz; 
	} 
	public Integer getStrength() { 
	  return Strength; 
	} 
	public void setStrength(Integer Strength) { 
	  this.Strength = Strength; 
	} 
	public Integer getDexterity() { 
	  return Dexterity; 
	} 
	public void setDexterity(Integer Dexterity) { 
	  this.Dexterity = Dexterity; 
	} 
	public Integer getVitality() { 
	  return Vitality; 
	} 
	public void setVitality(Integer Vitality) { 
	  this.Vitality = Vitality; 
	} 
	public Integer getEnergy() { 
	  return Energy; 
	} 
	public void setEnergy(Integer Energy) { 
	  this.Energy = Energy; 
	} 
	public Integer getMoney() { 
	  return Money; 
	} 
	public void setMoney(Integer Money) { 
	  this.Money = Money; 
	} 


} 