/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuildsForScoreQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   10/04/2016 07:10:45
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class GuildsForScoreQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer RowNumber;
	private String G_Name; 
	private Integer G_Count; 
	private Integer G_Score; 


	public String getG_Name() { 
	  return G_Name; 
	} 
	public void setG_Name(String G_Name) { 
	  this.G_Name = G_Name; 
	} 
	public Integer getG_Count() { 
	  return G_Count; 
	} 
	public void setG_Count(Integer G_Count) { 
	  this.G_Count = G_Count; 
	} 
	public Integer getG_Score() { 
	  return G_Score; 
	} 
	public void setG_Score(Integer G_Score) { 
	  this.G_Score = G_Score; 
	}
	public Integer getRowNumber() {
		return RowNumber;
	}
	public void setRowNumber(Integer rowNumber) {
		RowNumber = rowNumber;
	} 


} 