CREATE TABLE TRON2000.TA_VU_CARTA_LOG_ERR
(
  NRO_ERROR       NUMBER NOT NULL,
  DESCRIP_ERROR   VARCHAR2(1000),
    NOMBRE_ARCHIVO  VARCHAR2(200),
  COD_USR         VARCHAR2(100),
  FEC_REG         TIMESTAMP(6)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE TRON2000.TA_VU_CARTA_LOG_ERR ADD (CONSTRAINT TA_VU_CARTA_LOG_ERR_PKPRIMARY KEY(NRO_ERROR));

CREATE SEQUENCE TRON2000.SEQ_VU_CARTA_LOG_ERR
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;
