/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   25/02/2016 20:09:25
*/

Ext.define('MyApp.controller.GestionarCatalogo.CatalogoItemQueryController', {
    extend: 'Ext.app.Controller',

    stores: ['GestionarCatalogo.CatalogoItemQueryStore'],

    models: ['GestionarCatalogo.CatalogoItemQueryModel'],

    views: ['GestionarCatalogo.CatalogoItemQueryEdit', 'GestionarCatalogo.CatalogoItemQueryList'],

    refs: [
    	{
            ref: 'CatalogoItemQueryPanel',
            selector: 'panel'
        },
        {
            ref: 'CatalogoItemQueryList',
            selector: 'CatalogoItemQueryList'
        }
    ],

    init: function() {
        this.control({
            'CatalogoItemQueryList dataview': {
                itemdblclick: this.editRecord
            },
            'CatalogoItemQueryList button[action=add]': {
            	click: this.editRecord
            },
            'CatalogoItemQueryList button[action=delete]': {
                click: this.deleteRecord
            },
            'CatalogoItemQueryEdit button[action=save]': {
                click: this.updateRecord
            }
        });
    },

    editRecord: function(grid, record) {
        var edit = Ext.create('MyApp.view.GestionarCatalogo.CatalogoItemQueryEdit').show();
        if(record.data){
        	edit.down('form').loadRecord(record);
        	edit.setTitle('Editar');
        }else{
        	edit.setTitle('Agregar');
        }
    },
    
    updateRecord: function(button) {
    	
        var win = button.up('window');
        var form = win.down('form');
        var record = form.getRecord();
        var values = form.getValues();
        var store = Ext.getStore('GestionarCatalogo.CatalogoItemQueryStore');
        
        
        if (form.isValid()) {
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de GRABAR el registro?',function (btn) {
	            
	            if (btn == 'yes') {
                
                    if(win.title === 'Editar') {
                        record.set(values);
                    } else{
                        record = Ext.create('MyApp.model.GestionarCatalogo.CatalogoItemQueryModel');
                        record.set(values);
                        store.add(record);
                    }

                    win.close();	
                    store.sync({
                        success: function (batch, eOpts) {
                            store.load({params: {id_catalogo: null}});
                        }
                    });
	            }
	            
	     });
        
        }
    },
    deleteRecord: function(button) {
    	
    	var grid = this.getCatalogoItemQueryList();
    	var record = grid.getSelectionModel().getSelection(); 
    	var store = Ext.getStore('GestionarCatalogo.CatalogoItemQueryStore');
    	
    	if(record.length > 0){
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de ELIMINAR el registro?',function (btn) {
	                if (btn == 'yes') {
	             	   store.remove(record);
						store.sync({
					        success: function (batch, eOpts) {
					            store.load({params: {id_catalogo: null}});
					        }
					    });
	                }
	        });
    	}

    }
    
});