/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuiaRemisionQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   20/11/2016 11:35:44
*/

package pe.com.coravi.ventas.repository.model.dto;

import pe.com.kapcom.util.AbstractModel;

import java.util.List;

public class GuiaRemisionQuery extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia_remision; 
	private Integer id_comprobante_pago; 
	private String serie_docu_guia; 
	private String correlativo_docu_guia; 
	private String num_docu_guia; 
	private String fecha_inicio_traslado; 
	private Integer id_destinatario; 
	private String nombres_destinatario; 
	private Integer id_motivo_traslado; 
	private String descrip_motivo_traslado; 
	private String direccion_partida;
	private String codigo_departamento_partida;
	private String nombre_departamento_partida;
	private String codigo_provincia_partida;
	private String nombre_provincia_partida;
	private String codigo_distrito_partida;
	private String nombre_distrito_partida;
	private String direccion_llegada; 
	private String codigo_departamento_llegada;
	private String nombre_departamento_llegada;
	private String codigo_provincia_llegada;
	private String nombre_provincia_llegada;
	private String codigo_distrito_llegada;
	private String nombre_distrito_llegada;
	private Integer id_estado; 
	private String descrip_estado;

	List<GuiaRemisionDetalleQuery> guiaRemisionDetalleQueryList;

	public Integer getId_guia_remision() {
		return id_guia_remision;
	}

	public void setId_guia_remision(Integer id_guia_remision) {
		this.id_guia_remision = id_guia_remision;
	}

	public Integer getId_comprobante_pago() {
		return id_comprobante_pago;
	}

	public void setId_comprobante_pago(Integer id_comprobante_pago) {
		this.id_comprobante_pago = id_comprobante_pago;
	}

	public String getSerie_docu_guia() {
		return serie_docu_guia;
	}

	public void setSerie_docu_guia(String serie_docu_guia) {
		this.serie_docu_guia = serie_docu_guia;
	}

	public String getCorrelativo_docu_guia() {
		return correlativo_docu_guia;
	}

	public void setCorrelativo_docu_guia(String correlativo_docu_guia) {
		this.correlativo_docu_guia = correlativo_docu_guia;
	}

	public String getNum_docu_guia() {
		return num_docu_guia;
	}

	public void setNum_docu_guia(String num_docu_guia) {
		this.num_docu_guia = num_docu_guia;
	}

	public String getFecha_inicio_traslado() {
		return fecha_inicio_traslado;
	}

	public void setFecha_inicio_traslado(String fecha_inicio_traslado) {
		this.fecha_inicio_traslado = fecha_inicio_traslado;
	}

	public Integer getId_destinatario() {
		return id_destinatario;
	}

	public void setId_destinatario(Integer id_destinatario) {
		this.id_destinatario = id_destinatario;
	}

	public String getNombres_destinatario() {
		return nombres_destinatario;
	}

	public void setNombres_destinatario(String nombres_destinatario) {
		this.nombres_destinatario = nombres_destinatario;
	}

	public Integer getId_motivo_traslado() {
		return id_motivo_traslado;
	}

	public void setId_motivo_traslado(Integer id_motivo_traslado) {
		this.id_motivo_traslado = id_motivo_traslado;
	}

	public String getDescrip_motivo_traslado() {
		return descrip_motivo_traslado;
	}

	public void setDescrip_motivo_traslado(String descrip_motivo_traslado) {
		this.descrip_motivo_traslado = descrip_motivo_traslado;
	}

	public String getDireccion_partida() {
		return direccion_partida;
	}

	public void setDireccion_partida(String direccion_partida) {
		this.direccion_partida = direccion_partida;
	}

	public String getCodigo_departamento_partida() {
		return codigo_departamento_partida;
	}

	public void setCodigo_departamento_partida(String codigo_departamento_partida) {
		this.codigo_departamento_partida = codigo_departamento_partida;
	}

	public String getNombre_departamento_partida() {
		return nombre_departamento_partida;
	}

	public void setNombre_departamento_partida(String nombre_departamento_partida) {
		this.nombre_departamento_partida = nombre_departamento_partida;
	}

	public String getCodigo_provincia_partida() {
		return codigo_provincia_partida;
	}

	public void setCodigo_provincia_partida(String codigo_provincia_partida) {
		this.codigo_provincia_partida = codigo_provincia_partida;
	}

	public String getNombre_provincia_partida() {
		return nombre_provincia_partida;
	}

	public void setNombre_provincia_partida(String nombre_provincia_partida) {
		this.nombre_provincia_partida = nombre_provincia_partida;
	}

	public String getCodigo_distrito_partida() {
		return codigo_distrito_partida;
	}

	public void setCodigo_distrito_partida(String codigo_distrito_partida) {
		this.codigo_distrito_partida = codigo_distrito_partida;
	}

	public String getNombre_distrito_partida() {
		return nombre_distrito_partida;
	}

	public void setNombre_distrito_partida(String nombre_distrito_partida) {
		this.nombre_distrito_partida = nombre_distrito_partida;
	}

	public String getDireccion_llegada() {
		return direccion_llegada;
	}

	public void setDireccion_llegada(String direccion_llegada) {
		this.direccion_llegada = direccion_llegada;
	}

	public String getCodigo_departamento_llegada() {
		return codigo_departamento_llegada;
	}

	public void setCodigo_departamento_llegada(String codigo_departamento_llegada) {
		this.codigo_departamento_llegada = codigo_departamento_llegada;
	}

	public String getNombre_departamento_llegada() {
		return nombre_departamento_llegada;
	}

	public void setNombre_departamento_llegada(String nombre_departamento_llegada) {
		this.nombre_departamento_llegada = nombre_departamento_llegada;
	}

	public String getCodigo_provincia_llegada() {
		return codigo_provincia_llegada;
	}

	public void setCodigo_provincia_llegada(String codigo_provincia_llegada) {
		this.codigo_provincia_llegada = codigo_provincia_llegada;
	}

	public String getNombre_provincia_llegada() {
		return nombre_provincia_llegada;
	}

	public void setNombre_provincia_llegada(String nombre_provincia_llegada) {
		this.nombre_provincia_llegada = nombre_provincia_llegada;
	}

	public String getCodigo_distrito_llegada() {
		return codigo_distrito_llegada;
	}

	public void setCodigo_distrito_llegada(String codigo_distrito_llegada) {
		this.codigo_distrito_llegada = codigo_distrito_llegada;
	}

	public String getNombre_distrito_llegada() {
		return nombre_distrito_llegada;
	}

	public void setNombre_distrito_llegada(String nombre_distrito_llegada) {
		this.nombre_distrito_llegada = nombre_distrito_llegada;
	}

	public Integer getId_estado() {
		return id_estado;
	}

	public void setId_estado(Integer id_estado) {
		this.id_estado = id_estado;
	}

	public String getDescrip_estado() {
		return descrip_estado;
	}

	public void setDescrip_estado(String descrip_estado) {
		this.descrip_estado = descrip_estado;
	}

	public List<GuiaRemisionDetalleQuery> getGuiaRemisionDetalleQueryList() {
		return guiaRemisionDetalleQueryList;
	}

	public void setGuiaRemisionDetalleQueryList(List<GuiaRemisionDetalleQuery> guiaRemisionDetalleQueryList) {
		this.guiaRemisionDetalleQueryList = guiaRemisionDetalleQueryList;
	}
}