/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuiaRemisionDetalleQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   20/11/2016 11:35:51
*/

package pe.com.coravi.ventas.repository.model.dto;

import pe.com.kapcom.util.AbstractModel;

public class GuiaRemisionDetalleQuery extends AbstractModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia_remision_item; 
	private Integer id_guia_remision; 
	private Integer id_articulo; 
	private String nombre_articulo; 
	private Integer cantidad_articulo; 
	private Integer id_unidad_medida; 
	private String descrip_unidad_medida; 
	private Double peso_total; 
	private Integer id_estado; 
	private String descrip_estado; 


	public Integer getId_guia_remision_item() { 
	  return id_guia_remision_item; 
	} 
	public void setId_guia_remision_item(Integer id_guia_remision_item) { 
	  this.id_guia_remision_item = id_guia_remision_item; 
	} 
	public Integer getId_guia_remision() { 
	  return id_guia_remision; 
	} 
	public void setId_guia_remision(Integer id_guia_remision) { 
	  this.id_guia_remision = id_guia_remision; 
	} 
	public Integer getId_articulo() { 
	  return id_articulo; 
	} 
	public void setId_articulo(Integer id_articulo) { 
	  this.id_articulo = id_articulo; 
	} 
	public String getNombre_articulo() { 
	  return nombre_articulo; 
	} 
	public void setNombre_articulo(String nombre_articulo) { 
	  this.nombre_articulo = nombre_articulo; 
	} 
	public Integer getCantidad_articulo() { 
	  return cantidad_articulo; 
	} 
	public void setCantidad_articulo(Integer cantidad_articulo) { 
	  this.cantidad_articulo = cantidad_articulo; 
	} 
	public Integer getId_unidad_medida() { 
	  return id_unidad_medida; 
	} 
	public void setId_unidad_medida(Integer id_unidad_medida) { 
	  this.id_unidad_medida = id_unidad_medida; 
	} 
	public String getDescrip_unidad_medida() { 
	  return descrip_unidad_medida; 
	} 
	public void setDescrip_unidad_medida(String descrip_unidad_medida) { 
	  this.descrip_unidad_medida = descrip_unidad_medida; 
	} 
	public Double getPeso_total() { 
	  return peso_total; 
	} 
	public void setPeso_total(Double peso_total) { 
	  this.peso_total = peso_total; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 
	public String getDescrip_estado() { 
	  return descrip_estado; 
	} 
	public void setDescrip_estado(String descrip_estado) { 
	  this.descrip_estado = descrip_estado; 
	} 


} 