insert into map_info (cod_map,descrip_map) values (0,'Lorencia')
insert into map_info (cod_map,descrip_map) values (1,'Dungeon')
insert into map_info (cod_map,descrip_map) values (2,'Devias')
insert into map_info (cod_map,descrip_map) values (3,'Noria')
insert into map_info (cod_map,descrip_map) values (4,'Lost Tower')
insert into map_info (cod_map,descrip_map) values (5,'Exile')
insert into map_info (cod_map,descrip_map) values (6,'Arena/Stadium')
insert into map_info (cod_map,descrip_map) values (7,'Atlans')
insert into map_info (cod_map,descrip_map) values (8,'Tarkan')
insert into map_info (cod_map,descrip_map) values (9,'Devil Square 1')
insert into map_info (cod_map,descrip_map) values (10,'Icarus')
insert into map_info (cod_map,descrip_map) values (11,'Blood Castle 1')
insert into map_info (cod_map,descrip_map) values (12,'Blood Castle 2')
insert into map_info (cod_map,descrip_map) values (13,'Blood Castle 3')
insert into map_info (cod_map,descrip_map) values (14,'Blood Castle 4')
insert into map_info (cod_map,descrip_map) values (15,'Blood Castle 5')
insert into map_info (cod_map,descrip_map) values (16,'Blood Castle 6')
insert into map_info (cod_map,descrip_map) values (17,'Blood Castle 7')
insert into map_info (cod_map,descrip_map) values (18,'Chaos Castle 1')
insert into map_info (cod_map,descrip_map) values (19,'Chaos Castle 2')
insert into map_info (cod_map,descrip_map) values (20,'Chaos Castle 3')
insert into map_info (cod_map,descrip_map) values (21,'Chaos Castle 4')
insert into map_info (cod_map,descrip_map) values (22,'Chaos Castle 5')
insert into map_info (cod_map,descrip_map) values (23,'Chaos Castle 6')
insert into map_info (cod_map,descrip_map) values (24,'Kalima 1')
insert into map_info (cod_map,descrip_map) values (25,'Kalima 2')
insert into map_info (cod_map,descrip_map) values (26,'Kalima 3')
insert into map_info (cod_map,descrip_map) values (27,'Kalima 4')
insert into map_info (cod_map,descrip_map) values (28,'Kalima 5')
insert into map_info (cod_map,descrip_map) values (29,'Kalima 6')
insert into map_info (cod_map,descrip_map) values (30,'Valley of Loren')
insert into map_info (cod_map,descrip_map) values (31,'Land of Trial')
insert into map_info (cod_map,descrip_map) values (32,'Devil Square 2')
insert into map_info (cod_map,descrip_map) values (33,'Aida')
insert into map_info (cod_map,descrip_map) values (34,'Crywolf')
insert into map_info (cod_map,descrip_map) values (36,'Kalima 7')
insert into map_info (cod_map,descrip_map) values (37,'Kantru 1')
insert into map_info (cod_map,descrip_map) values (38,'Kantru 2')
insert into map_info (cod_map,descrip_map) values (39,'Kantru 3')
insert into map_info (cod_map,descrip_map) values (40,'Silent')
insert into map_info (cod_map,descrip_map) values (41,'Balgass Baracks')
insert into map_info (cod_map,descrip_map) values (42,'Balgass Refuge')
insert into map_info (cod_map,descrip_map) values (45,'Illusion Temple 1')
insert into map_info (cod_map,descrip_map) values (46,'Illusion Temple 2')
insert into map_info (cod_map,descrip_map) values (47,'Illusion Temple 3')
insert into map_info (cod_map,descrip_map) values (48,'Illusion Temple 4')
insert into map_info (cod_map,descrip_map) values (49,'Illusion Temple 5')
insert into map_info (cod_map,descrip_map) values (50,'Illusion Temple 6')
insert into map_info (cod_map,descrip_map) values (51,'Elbeland')
insert into map_info (cod_map,descrip_map) values (52,'BloodCastle 8')
insert into map_info (cod_map,descrip_map) values (53,'ChaosCastle 7')
insert into map_info (cod_map,descrip_map) values (56,'Swamp of Calmness')
insert into map_info (cod_map,descrip_map) values (57,'Raklion')
insert into map_info (cod_map,descrip_map) values (58,'Raklion Boss')
insert into map_info (cod_map,descrip_map) values (62,'Santa Town')
insert into map_info (cod_map,descrip_map) values (63,'Vulcanus')
insert into map_info (cod_map,descrip_map) values (64,'DuelArena')
insert into map_info (cod_map,descrip_map) values (65,'Doppelganger1')
insert into map_info (cod_map,descrip_map) values (66,'Doppelganger2')
insert into map_info (cod_map,descrip_map) values (67,'Doppelganger3')
insert into map_info (cod_map,descrip_map) values (68,'Doppelganger4')
insert into map_info (cod_map,descrip_map) values (69,'ImperialGuardian1')
insert into map_info (cod_map,descrip_map) values (70,'ImperialGuardian2')
insert into map_info (cod_map,descrip_map) values (71,'ImperialGuardian3')
insert into map_info (cod_map,descrip_map) values (72,'ImperialGuardian4')
insert into map_info (cod_map,descrip_map) values (79,'LorenMarket')
insert into map_info (cod_map,descrip_map) values (80,'Karutan1')
insert into map_info (cod_map,descrip_map) values (81,'Karutan2')
insert into map_info (cod_map,descrip_map) values (91,'Acheron')
insert into map_info (cod_map,descrip_map) values (96,'Debenter')
insert into map_info (cod_map,descrip_map) values (97,'ChaosCastleFinal')