/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The DocumentoBoletaDetalleQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   13/09/2016 05:03:11
*/

package pe.com.coravi.ventas.repository.model.mapper;

import org.apache.ibatis.session.RowBounds;
import pe.com.coravi.ventas.repository.model.dto.DocumentoBoletaDetalleQueryCriteria;
import pe.com.coravi.ventas.repository.model.dto.DocumentoBoletaDetalleQuery;

import java.util.List;
import java.util.Map;

public interface DocumentoBoletaDetalleQueryMapper {
   List<DocumentoBoletaDetalleQuery> getListQueryByCriteria(DocumentoBoletaDetalleQueryCriteria criteria);
   List<DocumentoBoletaDetalleQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<DocumentoBoletaDetalleQuery> getListQueryPaginationByCriteria(DocumentoBoletaDetalleQueryCriteria criteria, RowBounds rowBounds); 
   List<DocumentoBoletaDetalleQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(DocumentoBoletaDetalleQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
