ALTER TABLE OIM.RCEN_ASEG0001_TEMP ADD (COD_SISTEMA VARCHAR2(20 BYTE));
ALTER TABLE OIM.RCEN_ASEG0003_TEMP ADD (COD_SISTEMA VARCHAR2(20 BYTE));
ALTER TABLE OIM.RCEN_ASEG0004_TEMP ADD (COD_SISTEMA VARCHAR2(20 BYTE));

ALTER TABLE oim.RCEN_ASEG0001_TEMP
RENAME COLUMN "TIPO_MOVIMEINTO" TO "TIPO_MOVIMIENTO";

ALTER TABLE oim.RCEN_ASEG0001
RENAME COLUMN "TIPO_MOVIMEINTO" TO "TIPO_MOVIMIENTO";