package proyecto.param;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import proyecto.vo.Areanatural;
import proyecto.vo.Ejecutor;
import proyecto.vo.Fuentefinanciamiento;
import proyecto.vo.Proyecto;
import proyecto.vo.ProyectoEjecutor;
import proyecto.vo.ProyectoFteFto;

/**
 * Proyecto generated by hbm2java
 */
public class ProyectoParam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Proyecto proyecto;
	private Areanatural areanatural;
	private Ejecutor ejecutor;
	private Fuentefinanciamiento  ftefto;
	private ProyectoEjecutor proyectoEjecutor;
	private ProyectoFteFto proyectoFteFto;
	private Ejecutor ejecutorFinanciero;
	private Ejecutor ejecutorTecnico;
	
	public ProyectoParam(){
		proyecto=new Proyecto();
		areanatural=new Areanatural();
		ejecutor=new Ejecutor();
		ftefto=new Fuentefinanciamiento();
		proyectoEjecutor=new ProyectoEjecutor();
		proyectoFteFto=new ProyectoFteFto();
		ejecutorFinanciero=new Ejecutor();
		ejecutorTecnico=new Ejecutor();
	}


	public Proyecto getProyecto() {
		return proyecto;
	}


	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}


	public Areanatural getAreanatural() {
		return areanatural;
	}


	public void setAreanatural(Areanatural areanatural) {
		this.areanatural = areanatural;
	}


	public Ejecutor getEjecutor() {
		return ejecutor;
	}


	public void setEjecutor(Ejecutor ejecutor) {
		this.ejecutor = ejecutor;
	}


	public Fuentefinanciamiento getFtefto() {
		return ftefto;
	}


	public void setFtefto(Fuentefinanciamiento ftefto) {
		this.ftefto = ftefto;
	}


	public ProyectoEjecutor getProyectoEjecutor() {
		return proyectoEjecutor;
	}


	public void setProyectoEjecutor(ProyectoEjecutor proyectoEjecutor) {
		this.proyectoEjecutor = proyectoEjecutor;
	}


	public ProyectoFteFto getProyectoFteFto() {
		return proyectoFteFto;
	}


	public void setProyectoFteFto(ProyectoFteFto proyectoFteFto) {
		this.proyectoFteFto = proyectoFteFto;
	}


	public Ejecutor getEjecutorFinanciero() {
		return ejecutorFinanciero;
	}


	public void setEjecutorFinanciero(Ejecutor ejecutorFinanciero) {
		this.ejecutorFinanciero = ejecutorFinanciero;
	}


	public Ejecutor getEjecutorTecnico() {
		return ejecutorTecnico;
	}


	public void setEjecutorTecnico(Ejecutor ejecutorTecnico) {
		this.ejecutorTecnico = ejecutorTecnico;
	}
	
	
	
	

}
