package proyecto.param;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import proyecto.vo.Areanatural;
import proyecto.vo.Autor;
import proyecto.vo.Editorial;
import proyecto.vo.Ejecutor;
import proyecto.vo.Fuentefinanciamiento;
import proyecto.vo.Proyecto;
import proyecto.vo.ProyectoEjecutor;
import proyecto.vo.ProyectoFteFto;
import proyecto.vo.RecursoInformacion;
import proyecto.vo.Tema;

/**
 * Proyecto generated by hbm2java
 */
public class RecursoInformacionParam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RecursoInformacion recursoinformacion;
	private Areanatural areanatural;
	private Editorial editorial;
	private Autor autor;
	private Tema tema;
	public RecursoInformacionParam(){
		recursoinformacion=new RecursoInformacion();
		areanatural=new Areanatural();
		editorial=new Editorial();
		autor=new Autor();
		tema=new Tema();
	}


	


	public Areanatural getAreanatural() {
		return areanatural;
	}


	public void setAreanatural(Areanatural areanatural) {
		this.areanatural = areanatural;
	}





	public RecursoInformacion getRecursoinformacion() {
		return recursoinformacion;
	}





	public void setRecursoinformacion(RecursoInformacion recursoinformacion) {
		this.recursoinformacion = recursoinformacion;
	}





	public Editorial getEditorial() {
		return editorial;
	}





	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}





	public Autor getAutor() {
		return autor;
	}





	public void setAutor(Autor autor) {
		this.autor = autor;
	}





	public Tema getTema() {
		return tema;
	}





	public void setTema(Tema tema) {
		this.tema = tema;
	}


	
	
	

}
