/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by GeneratorCrud v.1.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 01:00:19
*/

package pe.com.acme.inavi.ws.controller;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import pe.com.acme.util.web.ControllerHelper;
import pe.com.acme.util.JsonReturnUtil;
import pe.com.acme.util.ModelWrapper;

import pe.com.acme.inavi.business.service.GestionarJornadaService;
import pe.com.acme.query.mybatis.model.JornadaLaboralQuery;
import pe.com.acme.query.mybatis.model.JornadaLaboralQueryCriteria;

@Controller
@RequestMapping("/GestionarJornada")
public class GestionarJornadaController extends ControllerHelper {

    private static Logger log = Logger.getLogger(GestionarJornadaController.class);

	@Autowired
	private GestionarJornadaService gestionarJornadaService;
	
	@RequestMapping(value="/list")
	public @ResponseBody Map<String,? extends Object> list(HttpServletRequest request) {
		try{
			JornadaLaboralQueryCriteria jornadaLaboralQueryCriteria = this.loadCriteria(request, JornadaLaboralQueryCriteria.class);
            List<JornadaLaboralQuery> listJornadaLaboralQuery = gestionarJornadaService.list(jornadaLaboralQueryCriteria);
			int count = gestionarJornadaService.countRecords(jornadaLaboralQueryCriteria);
			return JsonReturnUtil.success(listJornadaLaboralQuery,count);
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/create")
	public @ResponseBody Map<String,? extends Object> create(@RequestBody ModelWrapper<JornadaLaboralQuery> modelWrapper) {
		try{
			gestionarJornadaService.create(modelWrapper.getData());
			return JsonReturnUtil.success(modelWrapper.getData().getNum_anio());
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/update")
	public @ResponseBody Map<String,? extends Object> update(@RequestBody ModelWrapper<JornadaLaboralQuery> modelWrapper) {
		try{
			gestionarJornadaService.update(modelWrapper.getData());
			return JsonReturnUtil.success();
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/destroy")
	public @ResponseBody Map<String,? extends Object> destroy(@RequestBody ModelWrapper<JornadaLaboralQuery> modelWrapper) {
		try{
			gestionarJornadaService.destroy(modelWrapper.getData());
			return JsonReturnUtil.success();
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
}
