/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   05/03/2016 15:14:59
*/
Ext.define('MyApp.store.GestionarGuia.GuiaPesoQueryStore', {
    extend: 'Ext.data.Store',
    model: 'MyApp.model.GestionarGuia.GuiaPesoQueryModel',
    autoLoad: false,
    pageSize: 1000,
//    limit:10,
    sorters: {property: 'id_tipo_peso', direction: 'DESC'},
    groupField: 'descrip_tipo_peso',
    
    proxy: {
        type: 'ajax',
        api: {
        	read : '/InaviWSRestApp/api/GestionarGuia/listGuiaPesoQuery',
            create : '/InaviWSRestApp/api/GestionarGuia/createGuiaPesoQuery',
            update: '/InaviWSRestApp/api/GestionarGuia/updateGuiaPesoQuery',
            destroy: '/InaviWSRestApp/api/GestionarGuia/destroyGuiaPesoQuery'
        },
        reader: {
            type: 'json',
            rootProperty: 'data',
            successProperty: 'success',
            totalProperty: 'total',
            messageProperty: 'message'
        },
        writer: {
            type: 'json',
            writeAllFields: true,
            encode: false,
            rootProperty: 'data'
        },
        listeners: {
            exception: function(proxy, response, operation){	
                Ext.MessageBox.show({
                    title: 'REMOTE EXCEPTION',
                    msg: operation.getError(),
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK
                });
            }
        }
    }
});