/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The FacturaQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   19/07/2016 22:32:52
*/

package pe.com.acme.invoiceelec.model.mybatis.query.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.invoiceelec.model.mybatis.query.dto.FacturaQuery;
import pe.com.acme.invoiceelec.model.mybatis.query.dto.FacturaQueryCriteria;

public interface FacturaQueryMapper { 
   List<FacturaQuery> getListQueryByCriteria(FacturaQueryCriteria criteria);
   List<FacturaQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<FacturaQuery> getListQueryPaginationByCriteria(FacturaQueryCriteria criteria, RowBounds rowBounds); 
   List<FacturaQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(FacturaQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
