/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The NumeroDocQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   11/07/2016 20:42:05
*/

package pe.com.acme.invoiceelec.model.mybatis.query.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.invoiceelec.model.mybatis.query.dto.NumeroDocQuery;
import pe.com.acme.invoiceelec.model.mybatis.query.dto.NumeroDocQueryCriteria;

public interface NumeroDocQueryMapper { 
   List<NumeroDocQuery> getListQueryByCriteria(NumeroDocQueryCriteria criteria);
   List<NumeroDocQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<NumeroDocQuery> getListQueryPaginationByCriteria(NumeroDocQueryCriteria criteria, RowBounds rowBounds); 
   List<NumeroDocQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(NumeroDocQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
