/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   29/03/2016 22:54:29
*/

Ext.define('MyApp.view.MttoMembInfo.List' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.MttoMembInfoList',
    
    requires: ['MyApp.view.MttoMembInfo.Filter'],

    glyph:'xf022@FontAwesome',

    title : 'Mtto Cuentas',
    store: 'MttoMembInfo.MainStore',

    columns: [
		{
	    	header: "memb_guid",
			flex:115 / 100,
			dataIndex: 'memb_guid',
			hidden:true,
			sortable:true
		}
		,{
			header: "Usuario",
			flex:115 / 100,
			dataIndex: 'memb___id',
			hidden:false,
			sortable:true
		}
		,{
			header: "Alias (Apodo)",
			flex:115 / 100,
			dataIndex: 'memb_name',
			hidden:false,
			sortable:true
		}
		,{
			header: "Nombres",
			flex:115 / 100,
			dataIndex: 'nombres_completos',
			hidden:false,
			sortable:true
		}
		,{
			header: "Fecha Nacimiento",
			flex:115 / 100,
			dataIndex: 'fecha_nacimiento',
			hidden:false,
			sortable:true
		}
		,{
			header: "Genero",
			flex:115 / 100,
			dataIndex: 'descrip_gender',
			hidden:false,
			sortable:true
		}
		,{
			header: "Correo",
			flex:115 / 100,
			dataIndex: 'mail_addr',
			hidden:false,
			sortable:true
		}
		,{
			header: "Pais",
			flex:115 / 100,
			dataIndex: 'descrip_country',
			hidden:false,
			sortable:true
		}
		,{
			header: "Fecha Registro",
			flex:115 / 100,
			dataIndex: 'fecha_registro',
			hidden:false,
			sortable:true
		}
	],
	
	initComponent: function() {
		
		this.dockedItems = [
		     {
		          xtype: 'MttoMembInfoFilter'
		     },
			 {
	            xtype: 'toolbar',
	            items: [
				            {
				            	glyph:'xf0b0@FontAwesome',
				                text: 'Filtrar',
				                action: 'filter'
				            },
				            '-',
				            {
				            	glyph:'xf12d@FontAwesome',
				                text: 'Limpiar',
				                action: 'clearFilter'
				            },
				            '-',
				            {
				            	glyph:'xf055@FontAwesome',
				                text: 'Agregar',
				                action: 'add'
				            },
				            '-',
				            {
				            	glyph:'xf056@FontAwesome',
				                text: 'Eliminar',
				                action: 'delete'
				            }
			           ]
	        },
	        {
	            xtype: 'pagingtoolbar',
	            dock:'top',
	            store: 'MttoMembInfo.MainStore',
	            displayInfo: true
	        }
        ];
		
		this.callParent(arguments);
        this.on('render', this.loadStore, this);
	},
    loadStore: function() {
        this.getStore().load();
    }
});
