/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The BuscarPostulanteQueryCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   20/03/2016 22:48:39
*/

package sernanp.app.dao.query.domain;

public class BuscarPostulanteQueryCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private Integer idtipodocumento; 
	private String numerodoc; 
	private String fechanacimiento; 

	private String orderColumn;
	private String orderDirecction;
	
	public BuscarPostulanteQueryCriteria() {
		this.orderColumn = "1";
		this.orderDirecction = "ASC";
	}
	
	public Integer getIdtipodocumento() { 
	  return idtipodocumento; 
	} 
	public void setIdtipodocumento(Integer idtipodocumento) { 
	  this.idtipodocumento = idtipodocumento; 
	} 
	public String getNumerodoc() { 
	  return numerodoc; 
	} 
	public void setNumerodoc(String numerodoc) { 
	  this.numerodoc = numerodoc; 
	} 
	public String getFechanacimiento() { 
	  return fechanacimiento; 
	} 
	public void setFechanacimiento(String fechanacimiento) { 
	  this.fechanacimiento = fechanacimiento; 
	}

	public String getOrderColumn() {
		return orderColumn;
	}

	public void setOrderColumn(String orderColumn) {
		this.orderColumn = orderColumn;
	}

	public String getOrderDirecction() {
		return orderDirecction;
	}

	public void setOrderDirecction(String orderDirecction) {
		this.orderDirecction = orderDirecction;
	} 

} 