/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   17/03/2016 18:54:46
*/

Ext.define('MyApp.view.GestionarSaldo.GuiaSaldoQueryEdit', {
    extend: 'Ext.window.Window',
    alias : 'widget.GuiaSaldoQueryEdit',

    requires: ['Ext.form.Panel'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: 350,
    
    iconCls:'icon-pencil',

    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                id: 'form_submodel_GuiaSaldoQuery',
                padding: '5 5 0 5',
                border: false,
                style: 'background-color: #fff;',
                
                fieldDefaults: {
                    anchor: '100%',
                    labelAlign: 'left',
                    allowBlank: false,
                    combineErrors: true,
                    msgTarget: 'qtip',
                    labelWidth: 125
                },

                items: [
					{
					    allowBlank : true,
						xtype : 'textfield',
						hidden : true,
						editable : true,
						fieldLabel : 'id_guia_saldo',
						name : 'id_guia_saldo',
						disabled : false,
						readOnly : false
					}
					,{
					    allowBlank : true,
						xtype : 'textfield',
						hidden : true,
						editable : true,
						fieldLabel : 'id_guia',
						name : 'id_guia',
						disabled : false,
						readOnly : false
					}
					,{
					    xtype : 'textfield',
						hidden : false,
						vtype : 'soloNumeroDecimales',
						editable : true,
						fieldLabel : 'Monto',
						name : 'monto_amortizado',
						disabled : false,
						readOnly : false,
						listeners: {
							 'afterrender': function(f,e){

									 	f.setDisabled(true);
									 	
										Ext.Ajax.request({
									        method: 'GET',
									        url: '/InaviWSRestApp/api/GestionarSaldo/getDeudaPendiente',
									        success: function( result, request ){
									        	
									        	var json = Ext.JSON.decode(result.responseText);
									        	
									        	f.setDisabled(false);
									        	if(f.getValue() == ''){
									        		f.setValue(json.total_pendiente);
									        	}
									        	
									        }
									    });
							  }
						}
					}
					,{
					    xtype : 'datefield',
						hidden : false,
						editable : false,
						fieldLabel : 'Fecha Saldo',
						name : 'fecha_saldo',
						disabled : false,
						readOnly : false
					}
					,{
					    queryMode : 'local',
						xtype : 'combobox',
						hidden : false,
						emptyText : '-- Seleccione Opción --',
						editable : false,
						fieldLabel : 'Estado',
						name : 'id_estado',
						displayField : 'descrip_item',
						disabled : false,
						readOnly : false,
						store : {
								fields: ['valor_item','descrip_item'],
								proxy: {
							         type: 'ajax',
							         url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=estado_generico',
							         reader: {
							             type: 'json',
							             rootProperty: 'list'
							         }
						    	},
								autoLoad: true
					    },
						valueField : 'valor_item'
					}
                ]
            }
        ];
        
        this.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            //id:'buttons_GuiaSaldoQuery',
            ui: 'footer',
            items: ['->', {
            	iconCls:'icon-disk_black',
                itemId: 'save',
                text: 'Grabar',
                action: 'save'
            },{
            	iconCls:'icon-cross',
                text: 'Cancelar',
                scope: this,
                handler: this.close
            }]
        }];

        this.callParent(arguments);
    }
});
