/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   29/03/2016 22:54:29
*/

Ext.define('MyApp.view.GestionarSaldo.RegistroRapidoSaldoGridPanel' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.RegistroRapidoSaldoGridPanel',
    
    requires: ['Ext.grid.feature.GroupingSummary','Ext.grid.feature.Summary'],
    
    title : 'Detalle',
    renderTo: document.body,
    
    store : Ext.create('Ext.data.Store', {
    	
    	fields: [

    	         {name: 'descrip', type: 'string'},
    	         {name: 'importe', type: 'float'},
    	         {name: 'amortizado', type: 'float'},
    	         {name: 'deuda', type: 'float'}
    	         
    	        ],
    	        
    	proxy: {
    		type: 'ajax',
    		url: '/InaviWSRestApp/api/GestionarSaldo/listGuiaDeuda',
            reader: {
                type: 'json',
                rootProperty: 'data',
                successProperty: 'success',
                totalProperty: 'total',
                messageProperty: 'message'
            }
    	},
    	pageSize: 10,
    	autoLoad: false,
        listeners: {
            exception: function(proxy, response, operation){	
                Ext.MessageBox.show({
                    title: 'REMOTE EXCEPTION',
                    msg: operation.getError(),
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK
                });
            }
        }
    }),
    
    features: [
		        {
			        ftype: 'summary',
			        groupHeaderTpl: '{name} ({rows.length})',
			        hideGroupedHeader: true,
			        enableGroupingMenu: false,
			        startCollapsed: false
			    }
   ], 
   flex: 1,
    
    columns: [

		{
			header: "Descripción",
			flex:3,
			dataIndex: 'descrip',
			hidden:false,
			sortable:false
		},
		{
			header: "Importe",
			flex:2,
			dataIndex: 'importe',
			hidden:false,
			sortable:false
		},
		{
			header: "Amortizado",
			flex:2,
			dataIndex: 'amortizado',
			hidden:false,
			sortable:false
		},
		{
			text: "Deuda",
			flex:2,
			dataIndex: 'deuda',
			hidden:false,
			sortable:false,
            summaryType: 'sum',
            summaryRenderer: function(value, summaryData, dataIndex) {
                return ('<b>Total S/' + value + '</b>');
            }
		}
		
		
	],
	
	initComponent: function() {
		var me = this;
		this.callParent(arguments);
	}
});
