/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 22:42:35
*/

Ext.define('MyApp.view.GestionarSaldo.RegistroRapidoSaldoWindow', {
    extend: 'Ext.window.Window',
    alias : 'widget.RegistroRapidoSaldoWindow',

    requires: ['Ext.form.Panel',
               'MyApp.view.GestionarSaldo.RegistroRapidoSaldoGridPanel'],

	layout : 'fit',
	autoShow : true,
	modal : true,
	floating : true,
	resizable : false,
	width : 650,
	
//    iconCls:'icon-arrow_refresh',
    
	title:'Registro rapido',

    initComponent: function() {
        this.items = [
           
							{
								id:'form_registro_rapido',
								xtype: 'form',
								border: false,
								style: 'background-color: #fff;',
								
								fieldDefaults: {
									anchor: '100%',
									labelAlign: 'left',
									allowBlank: false,
									combineErrors: true,
									msgTarget: 'qtip',
				                    padding: '0 5 0 5',
									labelWidth: 125,
									margin: '5 0 0 0'
								},
								
			                    tbar: [

										{
											iconCls:'icon-disk_black',
											text : 'Grabar',
											handler:function(button){
												
												var win = button.up('window');
											     var form = win.down('form');
											     if (form.isValid()) {
											    	 

												    	 Ext.Msg.confirm('Confirmar','¿Estás seguro de GRABAR?',function (btn) {
												    		 if (btn == 'yes') {
															        Ext.Ajax.request({
															            method: 'GET',
															            url: '/InaviWSRestApp/api/GestionarSaldo/grabarImporteAmortizado',
															            params: form.getValues(),
															            success: function( result, request ){
															            													            	
															            	var json = Ext.JSON.decode(result.responseText);												            	
															            	
															            	if(json.success){
															            		
															            		var registroRapidoSaldoGridPanel = Ext.getCmp('registroRapidoSaldoGridPanel');
															            		id_cliente = form.getForm().findField('id_cliente');
															            		montoAmortizado = form.getForm().findField('montoAmortizado');
																	    		registroRapidoSaldoGridPanel.store.reload({
																	    			params: {
																	    				'id_cliente': id_cliente.getValue()
																	    			}
																	    		});
																	    		
																	    		montoAmortizado.setValue("");
															            		
															            		Ext.MessageBox.show({
															                        title: 'Resultado de proceso',
															                        msg: "Se grabaron los saldos con exito.",
															                        icon: Ext.MessageBox.INFO,
															                        buttons: Ext.Msg.OK
															                    });
															            		
															            	}else{
															            		
															            		Ext.MessageBox.show({
															                        title: 'REMOTE EXCEPTION',
															                        msg: json.message,
															                        icon: Ext.MessageBox.ERROR,
															                        buttons: Ext.Msg.OK
															                    });
															            		
															            	}
															            	
															            }
															        });
												    		 }
												    	 });
											    	 
											     }
											     
											}
										}
									],
								
								items: [

									{
										readOnly : false,
										allowBlank : true,
										store : {
											fields: ['id_persona','nombres'],
											proxy: {
												type: 'ajax',
												url: '/InaviWSRestApp/api/common/clientes',
												reader: {
													type: 'json',
													rootProperty: 'list'
												}
											},
											pageSize:10,
											autoLoad: false
										},
										queryMode : 'remote',
										displayField : 'nombres',
										hidden : false,
										xtype : 'combobox',
										// configure paging as we have ~23000 cities
										pageSize:10,
										// number of characters to type to initiate the search
										minChars:2,
										listConfig: {
											loadingText: 'Buscando...',
											emptyText: 'No se encontraron clientes.'
										},
										name : 'id_cliente',
										valueField : 'id_persona',
										emptyText : 'Ingrese nombres o apellidos.',
										fieldLabel : 'Cliente',
										disabled : false,
										editable : true,
									    listeners : {
									    	change: function(field, newValue, oldValue) {
									
									    		var registroRapidoSaldoGridPanel = Ext.getCmp('registroRapidoSaldoGridPanel');
									    		registroRapidoSaldoGridPanel.store.reload({
									    			params: {
									    				id_cliente: field.getValue()
									    			}
									    		});
									    		
									    	}
									    }
									}
									,{
										hidden : false,
										xtype : 'textfield',
										name : 'montoAmortizado',
										fieldLabel : 'Monto amortizado',
										disabled : false,
										editable : true
									},
                                    {

                                        readOnly : false,
                                        allowBlank : false,
                                        hidden : false,
                                        xtype : 'datefield',
                                        name : 'fecha_pago',
                                        fieldLabel : 'Fecha Pago',
                                        disabled : false,
                                        editable : true
                                    },
									{
										id:'registroRapidoSaldoGridPanel',
										xtype:'RegistroRapidoSaldoGridPanel',
										margin: '5 0 0 0'
									}

								]

							}

        ];



        this.callParent(arguments);      
    }
});
