/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The ResumenCompraVentaReportQueryCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   02/05/2016 01:18:20
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModelCriteria;

public class ResumenCompraVentaReportQueryCriteria extends AbstractModelCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private String fecha_jornada; 

	public ResumenCompraVentaReportQueryCriteria() {
		super();
	}
	
	public String getFecha_jornada() { 
	  return fecha_jornada; 
	} 
	public void setFecha_jornada(String fecha_jornada) { 
	  this.fecha_jornada = fecha_jornada; 
	} 

} 