/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The SaldoPorGuiaQueryCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   05/04/2016 23:50:34
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModelCriteria;

public class SaldoPorGuiaQueryCriteria extends AbstractModelCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia; 
	private String nombre_cliente; 

	public SaldoPorGuiaQueryCriteria() {
		super();
	}
	
	public Integer getId_guia() { 
	  return id_guia; 
	} 
	public void setId_guia(Integer id_guia) { 
	  this.id_guia = id_guia; 
	} 
	public String getNombre_cliente() { 
	  return nombre_cliente; 
	} 
	public void setNombre_cliente(String nombre_cliente) { 
	  this.nombre_cliente = nombre_cliente; 
	} 

} 