/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The SaldoQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   15/03/2016 00:45:25
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class SaldoQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_saldo; 
	private Integer id_cliente; 
	private String nombre_cliente; 
	private Integer id_cobrador; 
	private String nombre_cobrador; 
	private Integer id_tipo_concepto; 
	private String descrip_tipo_concepto; 
	private Integer id_tipo_mvto_saldo; 
	private String descrip_tipo_mvto_saldo; 
	private Double monto_recibido; 
	private Integer num_dia; 
	private Integer num_mes; 
	private Integer num_anio; 
	private String fecha_ingreso; 
	private Integer id_estado; 
	private String descrip_estado; 

	private java.util.List<GuiaSaldoQuery> listGuiaSaldoQuery; 

	public Integer getId_saldo() { 
	  return id_saldo; 
	} 
	public void setId_saldo(Integer id_saldo) { 
	  this.id_saldo = id_saldo; 
	} 
	public Integer getId_cliente() { 
	  return id_cliente; 
	} 
	public void setId_cliente(Integer id_cliente) { 
	  this.id_cliente = id_cliente; 
	} 
	public String getNombre_cliente() { 
	  return nombre_cliente; 
	} 
	public void setNombre_cliente(String nombre_cliente) { 
	  this.nombre_cliente = nombre_cliente; 
	} 
	public Integer getId_cobrador() { 
	  return id_cobrador; 
	} 
	public void setId_cobrador(Integer id_cobrador) { 
	  this.id_cobrador = id_cobrador; 
	} 
	public String getNombre_cobrador() { 
	  return nombre_cobrador; 
	} 
	public void setNombre_cobrador(String nombre_cobrador) { 
	  this.nombre_cobrador = nombre_cobrador; 
	} 
	public Integer getId_tipo_concepto() { 
	  return id_tipo_concepto; 
	} 
	public void setId_tipo_concepto(Integer id_tipo_concepto) { 
	  this.id_tipo_concepto = id_tipo_concepto; 
	} 
	public String getDescrip_tipo_concepto() { 
	  return descrip_tipo_concepto; 
	} 
	public void setDescrip_tipo_concepto(String descrip_tipo_concepto) { 
	  this.descrip_tipo_concepto = descrip_tipo_concepto; 
	} 
	public Integer getId_tipo_mvto_saldo() { 
	  return id_tipo_mvto_saldo; 
	} 
	public void setId_tipo_mvto_saldo(Integer id_tipo_mvto_saldo) { 
	  this.id_tipo_mvto_saldo = id_tipo_mvto_saldo; 
	} 
	public String getDescrip_tipo_mvto_saldo() { 
	  return descrip_tipo_mvto_saldo; 
	} 
	public void setDescrip_tipo_mvto_saldo(String descrip_tipo_mvto_saldo) { 
	  this.descrip_tipo_mvto_saldo = descrip_tipo_mvto_saldo; 
	} 
	public Double getMonto_recibido() { 
	  return monto_recibido; 
	} 
	public void setMonto_recibido(Double monto_recibido) { 
	  this.monto_recibido = monto_recibido; 
	} 
	public Integer getNum_dia() { 
	  return num_dia; 
	} 
	public void setNum_dia(Integer num_dia) { 
	  this.num_dia = num_dia; 
	} 
	public Integer getNum_mes() { 
	  return num_mes; 
	} 
	public void setNum_mes(Integer num_mes) { 
	  this.num_mes = num_mes; 
	} 
	public Integer getNum_anio() { 
	  return num_anio; 
	} 
	public void setNum_anio(Integer num_anio) { 
	  this.num_anio = num_anio; 
	} 
	public String getFecha_ingreso() { 
	  return fecha_ingreso; 
	} 
	public void setFecha_ingreso(String fecha_ingreso) { 
	  this.fecha_ingreso = fecha_ingreso; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 
	public String getDescrip_estado() { 
	  return descrip_estado; 
	} 
	public void setDescrip_estado(String descrip_estado) { 
	  this.descrip_estado = descrip_estado; 
	} 

	public java.util.List<GuiaSaldoQuery> getListGuiaSaldoQuery() { 
	  return listGuiaSaldoQuery; 
	} 
	public void setListGuiaSaldoQuery(java.util.List<GuiaSaldoQuery> listGuiaSaldoQuery) { 
	  this.listGuiaSaldoQuery = listGuiaSaldoQuery; 
	} 

} 