/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The TotalGuiasPeriodoTipoMvtoQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   28/07/2016 04:02:19
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class TotalGuiasPeriodoTipoMvtoQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer cant_aves_bruto; 
	private Integer cant_aves_bruto_revendido; 
	private Integer cant_aves_devolucion; 
	private Integer total_aves_devolucion; 
	private Integer total_aves_vendidas; 
	private Double total_peso_bruto; 
	private Double total_peso_bruto_revendido; 
	private Double total_peso_tara; 
	private Double total_peso_devolucion; 
	private Double total_tara_recalculo; 
	private Double total_peso_neto; 
	private Double total_importe; 


	public Integer getCant_aves_bruto() { 
	  return cant_aves_bruto; 
	} 
	public void setCant_aves_bruto(Integer cant_aves_bruto) { 
	  this.cant_aves_bruto = cant_aves_bruto; 
	} 
	public Integer getCant_aves_bruto_revendido() { 
	  return cant_aves_bruto_revendido; 
	} 
	public void setCant_aves_bruto_revendido(Integer cant_aves_bruto_revendido) { 
	  this.cant_aves_bruto_revendido = cant_aves_bruto_revendido; 
	} 
	public Integer getCant_aves_devolucion() { 
	  return cant_aves_devolucion; 
	} 
	public void setCant_aves_devolucion(Integer cant_aves_devolucion) { 
	  this.cant_aves_devolucion = cant_aves_devolucion; 
	} 
	public Integer getTotal_aves_devolucion() { 
	  return total_aves_devolucion; 
	} 
	public void setTotal_aves_devolucion(Integer total_aves_devolucion) { 
	  this.total_aves_devolucion = total_aves_devolucion; 
	} 
	public Integer getTotal_aves_vendidas() { 
	  return total_aves_vendidas; 
	} 
	public void setTotal_aves_vendidas(Integer total_aves_vendidas) { 
	  this.total_aves_vendidas = total_aves_vendidas; 
	} 
	public Double getTotal_peso_bruto() { 
	  return total_peso_bruto; 
	} 
	public void setTotal_peso_bruto(Double total_peso_bruto) { 
	  this.total_peso_bruto = total_peso_bruto; 
	} 
	public Double getTotal_peso_bruto_revendido() { 
	  return total_peso_bruto_revendido; 
	} 
	public void setTotal_peso_bruto_revendido(Double total_peso_bruto_revendido) { 
	  this.total_peso_bruto_revendido = total_peso_bruto_revendido; 
	} 
	public Double getTotal_peso_tara() { 
	  return total_peso_tara; 
	} 
	public void setTotal_peso_tara(Double total_peso_tara) { 
	  this.total_peso_tara = total_peso_tara; 
	} 
	public Double getTotal_peso_devolucion() { 
	  return total_peso_devolucion; 
	} 
	public void setTotal_peso_devolucion(Double total_peso_devolucion) { 
	  this.total_peso_devolucion = total_peso_devolucion; 
	} 
	public Double getTotal_tara_recalculo() { 
	  return total_tara_recalculo; 
	} 
	public void setTotal_tara_recalculo(Double total_tara_recalculo) { 
	  this.total_tara_recalculo = total_tara_recalculo; 
	} 
	public Double getTotal_peso_neto() { 
	  return total_peso_neto; 
	} 
	public void setTotal_peso_neto(Double total_peso_neto) { 
	  this.total_peso_neto = total_peso_neto; 
	} 
	public Double getTotal_importe() { 
	  return total_importe; 
	} 
	public void setTotal_importe(Double total_importe) { 
	  this.total_importe = total_importe; 
	} 


} 