/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 00:02:42
*/

Ext.define('MyApp.view.GestionarAplicacion.Edit', {
    extend: 'Ext.window.Window',
    alias : 'widget.GestionarAplicacionEdit',

    requires: ['Ext.form.Panel'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: '65%',

    glyph:'xf044@FontAwesome',

    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                items: [
							{
				                xtype: 'form',
				                id: 'form_crud_GestionarAplicacion',
				                padding: '5 5 0 5',
				                border: false,
				                style: 'background-color: #fff;',
				                title: 'Información de Aplicación',
				                glyph:'xf022@FontAwesome',
				                
				                fieldDefaults: {
					    			anchor: '100%',
				                    labelAlign: 'left',
				                    allowBlank: false,
				                    combineErrors: true,
				                    msgTarget: 'qtip',
                    				labelWidth: 125
			                	},

		                		items: [
											{
											    readOnly : false,
											    allowBlank : true,
											    hidden : true,
											    xtype : 'textfield',
											    name : 'id_aplicacion',
											    fieldLabel : 'Id Aplicación',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    allowBlank : false,
											    maxLength : 500,
											    hidden : false,
											    minLength : 1,
											    xtype : 'textfield',
											    name : 'nombre_aplicacion',
											    fieldLabel : 'Nombre',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    allowBlank : false,
											    maxLength : 1000,
											    hidden : false,
											    minLength : 1,
											    xtype : 'textfield',
											    name : 'url_aplicacion',
											    fieldLabel : 'Url',
											    disabled : false,
											    editable : true
											}
											,{
											    readOnly : false,
											    store : {
											    	fields: ['valor_item','descrip_item'],
											    	proxy: {
											    		type: 'ajax',
											    		url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=estado_generico',
											    		reader: {
											    			type: 'json',
											    			rootProperty: 'list'
											    		}
											    	},
											    	autoLoad: true
											    },
											    allowBlank : false,
											    queryMode : 'local',
											    displayField : 'descrip_item',
											    hidden : false,
											    xtype : 'combobox',
											    name : 'id_estado',
											    valueField : 'valor_item',
											    emptyText : '-- Seleccione Opción --',
											    fieldLabel : 'Estado',
											    disabled : false,
											    editable : false
											}
											,{
											    allowBlank : true,
											    hidden : true,
											    xtype : 'textfield',
											    name : 'tokenField',
											    fieldLabel : 'tokenField'
											}
										]
							}
							

							,{
					    		title: 'Perfiles',
					    		glyph:'xf022@FontAwesome',
					    		items: [{id:'subModel_PerfilAplicacionSubCrud', xtype:'PerfilAplicacionSubCrudList'}]
							}

                ]
            }
        ];
        
        this.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            //id:'buttons',
            ui: 'footer',
            items: ['->', {
            	glyph:'xf0c7@FontAwesome',
                itemId: 'save',
                text: 'Grabar',
                action: 'save'
            },{
            	glyph:'xf00d@FontAwesome',
                text: 'Cancelar',
                scope: this,
                handler: this.close
            }]
        }];

        this.callParent(arguments);      
    }
});
