/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 22:42:35
*/

Ext.define('MyApp.view.GestionarGuia.CambiarPrecioWindow', {
    extend: 'Ext.window.Window',
    alias : 'widget.CambiarPrecioWindow',

    requires: ['Ext.form.Panel',
               'MyApp.view.GestionarGuia.CambiarPrecioGridPanel','Ext.layout.container.Border'],

	layout : 'fit',
	autoShow : true,
	modal : true,
	floating : true,
	resizable : false,
	width : 650,
	
//    iconCls:'icon-arrow_refresh',
    
	title:'Cambiar precios por fecha',

    initComponent: function() {
        this.items = [
           
							{
								id:'form_cambiar_precio',
								xtype: 'form',
								border: false,
								style: 'background-color: #fff;',
								
								fieldDefaults: {
									anchor: '100%',
									labelAlign: 'left',
									allowBlank: false,
									combineErrors: true,
									msgTarget: 'qtip',
				                    padding: '0 5 0 5',
									labelWidth: 125,
									margin: '5 0 0 0'
								},
								
			                    tbar: [

										{
											iconCls:'icon-cog_start',
											text : 'Calcular',
											handler:function(button){
												
												var win = button.up('window');
											     var form = win.down('form');
											     if (form.isValid()) {
											    	var cambiarPrecioGridPanel = Ext.getCmp('cambiarPrecioGridPanel');											        	
											        cambiarPrecioGridPanel.store.reload();
											     }
											     
											}
										},
										{
											iconCls:'icon-disk_black',
											text : 'Grabar',
											handler:function(button){
												 var win = button.up('window');
											     var form = win.down('form');
											     if (form.isValid()) {
											        	
											    	 Ext.Msg.confirm('Confirmar','¿Estás seguro de GRABAR?',function (btn) {
												            
												            if (btn == 'yes') {
														        Ext.Ajax.request({
														            method: 'GET',
														            url: '/InaviWSRestApp/api/GestionarGuia/grabarCambioPrecio',
														            params: form.getValues(),
														            success: function( result, request ){
														            													            	
														            	var json = Ext.JSON.decode(result.responseText);												            	
														            	
														            	if(json.success){
														            		
														            		Ext.MessageBox.show({
														                        title: 'Resultado de proceso',
														                        msg: "Se cambiaron los precios con exito.",
														                        icon: Ext.MessageBox.INFO,
														                        buttons: Ext.Msg.OK
														                    });
														            		
														            	}else{
														            		
														            		Ext.MessageBox.show({
														                        title: 'REMOTE EXCEPTION',
														                        msg: "No se pudo procesar la solicitud.",
														                        icon: Ext.MessageBox.ERROR,
														                        buttons: Ext.Msg.OK
														                    });
														            		
														            	}
														            	
														            }
														        });
												            }
												     });
											    	 
											     }
											}
										}
			                          ],

								items: [
									{
										
										readOnly : false,
										allowBlank : false,
										hidden : false,
										xtype : 'datefield',
										name : 'fecha_jornada',
										fieldLabel : 'Fecha Jornada',
										disabled : false,
										editable : true
									},{
										hidden : false,
										xtype : 'textfield',
										name : 'valor',
										fieldLabel : 'Valor',
										disabled : false,
										editable : true
									},
									{
										id:'cambiarPrecioGridPanel',
										xtype:'CambiarPrecioGridPanel',
										margin: '5 0 0 0'
									}

								]

							}

        ];



        this.callParent(arguments);      
    }
});
