/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 22:42:35
*/

Ext.define('MyApp.view.GestionarGuia.ReporteResumenCompraVentaWindow', {
    extend: 'Ext.window.Window',
    alias : 'widget.ReporteResumenCompraVentaWindow',

    requires: ['Ext.form.Panel'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: 350,

    iconCls:'icon-chart_curve',
	title:'Reporte',

    initComponent: function() {
        this.items = [
           
							
							
							{
								xtype: 'form',
								padding: '5 5 0 5',
								border: false,
								style: 'background-color: #fff;',
								fieldDefaults: {
									anchor: '100%',
									labelAlign: 'left',
									allowBlank: false,
									combineErrors: true,
									msgTarget: 'qtip',
									labelWidth: 125
								},

								items: [
									{
										readOnly : false,
										allowBlank : false,
										hidden : false,
										xtype : 'datefield',
										name : 'fecha_jornada',
										fieldLabel : 'Fecha Jornada',
										disabled : false,
										editable : true
									},
									{
										readOnly : false,
										allowBlank : false,
										store : {
											data:[
												{
													doc_type: 'pdf', descrip_doc_type:'PDF'
												},
												{
													doc_type: 'docx', descrip_doc_type:'Word'
												},
												{
													doc_type: 'xlsx', descrip_doc_type:'Excel'
												}
											]
										},
										queryMode : 'local',
										displayField : 'descrip_doc_type',
										hidden : false,
										xtype : 'combobox',
										name : 'doc_type',
										valueField : 'doc_type',
										emptyText : '-- Seleccione --',
										fieldLabel : 'Tipo Documento',
										disabled : false,
										editable : false,
										value:'pdf'
									}

								],

								buttons : [
									{
										iconCls:'icon-cog_start',
										text:'Generar',
										handler:function () {
											var form = this.up('form').getForm();
											var encodedFilename = Ext.urlEncode(form.getValues());
											if (form.isValid()) {
												window.open('/InaviWSRestApp/api/report/resumenCompraVenta?'+ encodedFilename, '_blank');
											}
										}
									}
								]

							}

        ];



        this.callParent(arguments);      
    }
});
