//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 08:21:21 PM PET 
//


package pe.com.focus.generator.crud.extjs.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Entity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="classEntity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="primaryKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="classMapper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="joinProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="otherProperties" type="{http://www.focus.com.pe/generator/crud/extjs}Properties" minOccurs="0"/>
 *         &lt;element name="entities" type="{http://www.focus.com.pe/generator/crud/extjs}Entities" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entity", propOrder = {
    "classEntity",
    "primaryKey",
    "classMapper",
    "joinProperty",
    "returnProperty",
    "otherProperties",
    "entities"
})
public class Entity {

    @XmlElement(required = true)
    protected String classEntity;
    @XmlElement(required = true)
    protected String primaryKey;
    protected String classMapper;
    protected String joinProperty;
    protected String returnProperty;
    protected Properties otherProperties;
    protected Entities entities;

    /**
     * Gets the value of the classEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassEntity() {
        return classEntity;
    }

    /**
     * Sets the value of the classEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassEntity(String value) {
        this.classEntity = value;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryKey(String value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the classMapper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassMapper() {
        return classMapper;
    }

    /**
     * Sets the value of the classMapper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassMapper(String value) {
        this.classMapper = value;
    }

    /**
     * Gets the value of the joinProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinProperty() {
        return joinProperty;
    }

    /**
     * Sets the value of the joinProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinProperty(String value) {
        this.joinProperty = value;
    }

    /**
     * Gets the value of the returnProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnProperty() {
        return returnProperty;
    }

    /**
     * Sets the value of the returnProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnProperty(String value) {
        this.returnProperty = value;
    }

    /**
     * Gets the value of the otherProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getOtherProperties() {
        return otherProperties;
    }

    /**
     * Sets the value of the otherProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setOtherProperties(Properties value) {
        this.otherProperties = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link Entities }
     *     
     */
    public Entities getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entities }
     *     
     */
    public void setEntities(Entities value) {
        this.entities = value;
    }

}
