//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 08:21:21 PM PET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.focus.com.pe/generator/crud/extjs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pe.com.focus.generator.crud.extjs.schema;
