package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Actividadturismo generated by hbm2java
 */
public class Actividadturismo  {

	private int idactividadturismo;
	private String nombreactividadturismo;
	private String detalleactividadturismo;
	private Tipoturismo tipoturismo;

	
	
	public Actividadturismo() {
		tipoturismo=new Tipoturismo();
	}
	public int getIdactividadturismo() {
		return idactividadturismo;
	}
	public void setIdactividadturismo(int idactividadturismo) {
		this.idactividadturismo = idactividadturismo;
	}
    public Tipoturismo getTipoturismo() {
		return tipoturismo;
	}
    public void setTipoturismo(Tipoturismo tipoturismo) {
		this.tipoturismo = tipoturismo;
	}
	public String getNombreactividadturismo() {
		return this.nombreactividadturismo;
	}

	public void setNombreactividadturismo(String nombreactividadturismo) {
		this.nombreactividadturismo = nombreactividadturismo;
	}

	public String getDetalleactividadturismo() {
		return this.detalleactividadturismo;
	}

	public void setDetalleactividadturismo(String detalleactividadturismo) {
		this.detalleactividadturismo = detalleactividadturismo;
	}

	
}
