package proyecto.vo;

import java.util.ArrayList;
import java.util.List;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Tipoproyecto generated by hbm2java
 */
public class Documento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int iddocumento;
	private int codigodocumento;
	private String desdocumento;
	private List<Archivo> listaArchivo;
	
	public Documento() {
		listaArchivo=new ArrayList<Archivo>();
	}

	public int getIddocumento() {
		return iddocumento;
	}

	public void setIddocumento(int iddocumento) {
		this.iddocumento = iddocumento;
	}

	public String getDesdocumento() {
		return desdocumento;
	}

	public void setDesdocumento(String desdocumento) {
		this.desdocumento = desdocumento;
	}

	public List<Archivo> getListaArchivo() {
		return listaArchivo;
	}

	public void setListaArchivo(List<Archivo> listaArchivo) {
		this.listaArchivo = listaArchivo;
	}

	public int getCodigodocumento() {
		return codigodocumento;
	}

	public void setCodigodocumento(int codigodocumento) {
		this.codigodocumento = codigodocumento;
	}

	
	

}
