package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Ejecutor generated by hbm2java
 */
public class Ejecutor implements java.io.Serializable {

	private int idejecutor;
	private Personajuridica personajuridica;
	private List<Proyecto> proyectos = new ArrayList<Proyecto>();

	public Ejecutor() {
		personajuridica=new Personajuridica();
	}

	public Ejecutor(Personajuridica personajuridica) {
		this.personajuridica = personajuridica;
	}

	public Ejecutor(Personajuridica personajuridica, List<Proyecto> proyectos) {
		this.personajuridica = personajuridica;
		this.proyectos = proyectos;
	}

	public int getIdejecutor() {
		return this.idejecutor;
	}

	public void setIdejecutor(int idejecutor) {
		this.idejecutor = idejecutor;
	}

	public Personajuridica getPersonajuridica() {
		return this.personajuridica;
	}

	public void setPersonajuridica(Personajuridica personajuridica) {
		this.personajuridica = personajuridica;
	}

	public List<Proyecto> getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(List<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}

}
