package proyecto.vo;

import java.util.Date;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Areanatural generated by hbm2java
 */
public class Idioma implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ididioma;
	private String nombreidioma;
	
	
	public Idioma(){
		
	}
	
	public int getIdidioma() {
		return ididioma;
	}
	public void setIdidioma(int ididioma) {
		this.ididioma = ididioma;
	}
	public String getNombreidioma() {
		return nombreidioma;
	}
	public void setNombreidioma(String nombreidioma) {
		this.nombreidioma = nombreidioma;
	}
	
	
	
	

}
