package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;

/**
 * Persona generated by hbm2java
 */
public class Persona implements Serializable{  

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpersona;
	private String direccion; 
	private String telefono; 
	private String correopersonal;
	private String correoinstitucional;
	private String ruc;
	private Ubigeo ubigeo;
    private Pais pais;
    
    private String empresa;
	
    // JCEV 17-10-2012
    private String nombrepersonajuridica;
    
	public Persona() {
		pais=new Pais();
		ubigeo=new Ubigeo();
	}

	public int getIdpersona() {
		return idpersona;
	}

	public void setIdpersona(int idpersona) {
		this.idpersona = idpersona;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreopersonal() {
		return correopersonal;
	}

	public void setCorreopersonal(String correopersonal) {
		this.correopersonal = correopersonal;
	}

	public String getCorreoinstitucional() {
		return correoinstitucional;
	}

	public void setCorreoinstitucional(String correoinstitucional) {
		this.correoinstitucional = correoinstitucional;
	}

	public String getRuc() {
		return ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public Ubigeo getUbigeo() {
		return ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	public Pais getPais() {
		return pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public String getEmpresa() {
		return empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	public String getNombrepersonajuridica() {
		return nombrepersonajuridica;
	}

	public void setNombrepersonajuridica(String nombrepersonajuridica) {
		this.nombrepersonajuridica = nombrepersonajuridica;
	}
	
}