package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Proyecto generated by hbm2java
 */
public class ProyectoEjecutor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idproyectoejecutor;
	private int idcodigo;
	private Proyecto proyecto;
	private Ejecutor ejecutor;
	private Tipo tipoejecutor;
	
	
	
	public ProyectoEjecutor() {
		proyecto=new Proyecto();
		ejecutor=new Ejecutor();
		tipoejecutor=new Tipo();
	}


	
	
	
	





	public int getIdcodigo() {
		return idcodigo;
	}











	public void setIdcodigo(int idcodigo) {
		this.idcodigo = idcodigo;
	}











	public int getIdproyectoejecutor() {
		return idproyectoejecutor;
	}





	public void setIdproyectoejecutor(int idproyectoejecutor) {
		this.idproyectoejecutor = idproyectoejecutor;
	}





	public Proyecto getProyecto() {
		return proyecto;
	}


	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}


	public Ejecutor getEjecutor() {
		return ejecutor;
	}


	public void setEjecutor(Ejecutor ejecutor) {
		this.ejecutor = ejecutor;
	}


	public Tipo getTipoejecutor() {
		return tipoejecutor;
	}


	public void setTipoejecutor(Tipo tipoejecutor) {
		this.tipoejecutor = tipoejecutor;
	}
	
	


	

	
	
	

}
