package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

/**
 * Puestoscontrol generated by hbm2java
 */
public class Puestoscontrol implements java.io.Serializable {

	private int idpuestoscontrol;
	private Areanatural areanatural;
	private Byte turismo;

	public Puestoscontrol() {
	}

	public Puestoscontrol(Areanatural areanatural) {
		this.areanatural = areanatural;
	}

	public Puestoscontrol(Areanatural areanatural, Byte turismo) {
		this.areanatural = areanatural;
		this.turismo = turismo;
	}

	public int getIdpuestoscontrol() {
		return this.idpuestoscontrol;
	}

	public void setIdpuestoscontrol(int idpuestoscontrol) {
		this.idpuestoscontrol = idpuestoscontrol;
	}

	public Areanatural getAreanatural() {
		return this.areanatural;
	}

	public void setAreanatural(Areanatural areanatural) {
		this.areanatural = areanatural;
	}

	public Byte getTurismo() {
		return this.turismo;
	}

	public void setTurismo(Byte turismo) {
		this.turismo = turismo;
	}

}
