package proyecto.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Areanatural generated by hbm2java
 */
public class RecursoInformacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrecursoinformacion;
	private String codigorecursoinformacion;
	private String titulo;
	private Date fechaingreso;
	private String descripcion;
	private String titulooriginal;
	private String isbn;
	private String codigosgd;
	private Date fecharegistro;
	private int numeropaginas;
	private int aniopublicacion;
	private Tipo tiporecursoinformacion;
	private Tipo mediorecursoinformacion;
	private TematicaRecursoInformacion tematicarecursoinformacion;
	private Idioma idioma;
	private int flagtemporal;
	private int flagrecursoinformacion;
	private int numerorecursoinformacion;
	private int numerorecursoinformacionarea;
	private Areanatural sedebiblioteca;
	private AprobacionRecursoInformacion aprobacionrecursoinformacion;
	private List<RecursoInformacionArchivo> listaRecursoInformacionArchivo;
	private List<RecursoInformacionEditorial> listaRecursoInformacionEditorial;
	private List<RecursoInformacionAutor> listaRecursoInformacionAutor;
	private List<RecursoInformacionTema> listaRecursoInformacionTema;
	private List<RecursoInformacionAreanatural> listaRecursoInformacionAreanatural;
	
	
	public RecursoInformacion(){
		tematicarecursoinformacion=new TematicaRecursoInformacion();
		tiporecursoinformacion=new Tipo();
		mediorecursoinformacion=new Tipo();
		listaRecursoInformacionEditorial=new ArrayList<RecursoInformacionEditorial>();
		listaRecursoInformacionAutor=new ArrayList<RecursoInformacionAutor>();
		listaRecursoInformacionTema=new ArrayList<RecursoInformacionTema>();
		listaRecursoInformacionAreanatural=new ArrayList<RecursoInformacionAreanatural>();
		sedebiblioteca=new Areanatural();
		idioma=new Idioma();
		aprobacionrecursoinformacion=new AprobacionRecursoInformacion();
		listaRecursoInformacionArchivo=new ArrayList<RecursoInformacionArchivo>();
		
		//
		/*
		RecursoInformacionArchivo rad=new RecursoInformacionArchivo();
		rad.getTipoarchivo().setIdtipo(ValueConstants.TIPO_FILE_DOCUMENTO);
		RecursoInformacionArchivo rai=new RecursoInformacionArchivo();
		rai.getTipoarchivo().setIdtipo(ValueConstants.TIPO_FILE_IMAGEN);
		listaRecursoInformacionArchivo.add(rad);
		listaRecursoInformacionArchivo.add(rai);
		*/
	}


	public RecursoInformacion(int idrecursoinformacion){
		this();
		this.idrecursoinformacion=idrecursoinformacion;
	}
	
	
	
	
	
	


	


	public int getNumerorecursoinformacion() {
		return numerorecursoinformacion;
	}


	public void setNumerorecursoinformacion(int numerorecursoinformacion) {
		this.numerorecursoinformacion = numerorecursoinformacion;
	}


	public int getNumerorecursoinformacionarea() {
		return numerorecursoinformacionarea;
	}


	public void setNumerorecursoinformacionarea(int numerorecursoinformacionarea) {
		this.numerorecursoinformacionarea = numerorecursoinformacionarea;
	}


	public Areanatural getSedebiblioteca() {
		return sedebiblioteca;
	}


	public void setSedebiblioteca(Areanatural sedebiblioteca) {
		this.sedebiblioteca = sedebiblioteca;
	}


	public int getIdrecursoinformacion() {
		return idrecursoinformacion;
	}


	public void setIdrecursoinformacion(int idrecursoinformacion) {
		this.idrecursoinformacion = idrecursoinformacion;
	}


	public String getTitulo() {
		return titulo;
	}


	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}


	

	public Date getFechaingreso() {
		return fechaingreso;
	}


	public void setFechaingreso(Date fechaingreso) {
		this.fechaingreso = fechaingreso;
	}


	public String getDescripcion() {
		return descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}


	


	public String getTitulooriginal() {
		return titulooriginal;
	}


	public void setTitulooriginal(String titulooriginal) {
		this.titulooriginal = titulooriginal;
	}


	public String getIsbn() {
		return isbn;
	}


	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}


	public String getCodigosgd() {
		return codigosgd;
	}


	public void setCodigosgd(String codigosgd) {
		this.codigosgd = codigosgd;
	}


	
	

	public Date getFecharegistro() {
		return fecharegistro;
	}


	public void setFecharegistro(Date fecharegistro) {
		this.fecharegistro = fecharegistro;
	}


	public int getNumeropaginas() {
		return numeropaginas;
	}


	public void setNumeropaginas(int numeropaginas) {
		this.numeropaginas = numeropaginas;
	}


	public Tipo getTiporecursoinformacion() {
		return tiporecursoinformacion;
	}


	public void setTiporecursoinformacion(Tipo tiporecursoinformacion) {
		this.tiporecursoinformacion = tiporecursoinformacion;
	}


	public Tipo getMediorecursoinformacion() {
		return mediorecursoinformacion;
	}


	public void setMediorecursoinformacion(Tipo mediorecursoinformacion) {
		this.mediorecursoinformacion = mediorecursoinformacion;
	}


	public TematicaRecursoInformacion getTematicarecursoinformacion() {
		return tematicarecursoinformacion;
	}


	public void setTematicarecursoinformacion(
			TematicaRecursoInformacion tematicarecursoinformacion) {
		this.tematicarecursoinformacion = tematicarecursoinformacion;
	}


	public Idioma getIdioma() {
		return idioma;
	}


	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}


	
	


	public int getFlagtemporal() {
		return flagtemporal;
	}


	public void setFlagtemporal(int flagtemporal) {
		this.flagtemporal = flagtemporal;
	}


	public String getCodigorecursoinformacion() {
		return codigorecursoinformacion;
	}


	public void setCodigorecursoinformacion(String codigorecursoinformacion) {
		this.codigorecursoinformacion = codigorecursoinformacion;
	}


	public int getFlagrecursoinformacion() {
		return flagrecursoinformacion;
	}


	public void setFlagrecursoinformacion(int flagrecursoinformacion) {
		this.flagrecursoinformacion = flagrecursoinformacion;
	}


	public List<RecursoInformacionArchivo> getListaRecursoInformacionArchivo() {
		return listaRecursoInformacionArchivo;
	}


	public void setListaRecursoInformacionArchivo(
			List<RecursoInformacionArchivo> listaRecursoInformacionArchivo) {
		this.listaRecursoInformacionArchivo = listaRecursoInformacionArchivo;
	}


	public List<RecursoInformacionEditorial> getListaRecursoInformacionEditorial() {
		return listaRecursoInformacionEditorial;
	}


	public void setListaRecursoInformacionEditorial(
			List<RecursoInformacionEditorial> listaRecursoInformacionEditorial) {
		this.listaRecursoInformacionEditorial = listaRecursoInformacionEditorial;
	}


	public List<RecursoInformacionAutor> getListaRecursoInformacionAutor() {
		return listaRecursoInformacionAutor;
	}


	public void setListaRecursoInformacionAutor(
			List<RecursoInformacionAutor> listaRecursoInformacionAutor) {
		this.listaRecursoInformacionAutor = listaRecursoInformacionAutor;
	}


	public List<RecursoInformacionTema> getListaRecursoInformacionTema() {
		return listaRecursoInformacionTema;
	}


	public void setListaRecursoInformacionTema(
			List<RecursoInformacionTema> listaRecursoInformacionTema) {
		this.listaRecursoInformacionTema = listaRecursoInformacionTema;
	}


	public int getAniopublicacion() {
		return aniopublicacion;
	}


	public void setAniopublicacion(int aniopublicacion) {
		this.aniopublicacion = aniopublicacion;
	}


	public List<RecursoInformacionAreanatural> getListaRecursoInformacionAreanatural() {
		return listaRecursoInformacionAreanatural;
	}


	public void setListaRecursoInformacionAreanatural(
			List<RecursoInformacionAreanatural> listaRecursoInformacionAreanatural) {
		this.listaRecursoInformacionAreanatural = listaRecursoInformacionAreanatural;
	}


	public AprobacionRecursoInformacion getAprobacionrecursoinformacion() {
		return aprobacionrecursoinformacion;
	}


	public void setAprobacionrecursoinformacion(
			AprobacionRecursoInformacion aprobacionrecursoinformacion) {
		this.aprobacionrecursoinformacion = aprobacionrecursoinformacion;
	}


	
	
	
	
	
	
	

}
