package proyecto.vo;


// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Areanatural generated by hbm2java
 */
public class RecursoInformacionAutor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idrecursoinformacionautor;
	private int idcodigo;
	private int idrecursoinformacion;
	private Autor autor;
	
	
	public RecursoInformacionAutor(){
		autor=new Autor();
	}


	public int getIdrecursoinformacionautor() {
		return idrecursoinformacionautor;
	}


	public void setIdrecursoinformacionautor(int idrecursoinformacionautor) {
		this.idrecursoinformacionautor = idrecursoinformacionautor;
	}


	public int getIdcodigo() {
		return idcodigo;
	}


	public void setIdcodigo(int idcodigo) {
		this.idcodigo = idcodigo;
	}


	public int getIdrecursoinformacion() {
		return idrecursoinformacion;
	}


	public void setIdrecursoinformacion(int idrecursoinformacion) {
		this.idrecursoinformacion = idrecursoinformacion;
	}


	public Autor getAutor() {
		return autor;
	}


	public void setAutor(Autor autor) {
		this.autor = autor;
	}


	
	

	

	
	
	
	

}
