package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Tipoproyecto generated by hbm2java
 */
public class TematicaRecursoInformacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtematicarecursoinformacion;
	private String nombretematicarecursoinformacion;
	
	
	
	public TematicaRecursoInformacion() {
	
	}



	public int getIdtematicarecursoinformacion() {
		return idtematicarecursoinformacion;
	}



	public void setIdtematicarecursoinformacion(int idtematicarecursoinformacion) {
		this.idtematicarecursoinformacion = idtematicarecursoinformacion;
	}



	public String getNombretematicarecursoinformacion() {
		return nombretematicarecursoinformacion;
	}



	public void setNombretematicarecursoinformacion(
			String nombretematicarecursoinformacion) {
		this.nombretematicarecursoinformacion = nombretematicarecursoinformacion;
	}

	
		

}
