package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Tipoproyecto generated by hbm2java
 */
public class Tipotelefono implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtipotelefono;
	private String nombretipotelefono;

	
	
	public Tipotelefono() {
	}



	public int getIdtipotelefono() {
		return idtipotelefono;
	}



	public void setIdtipotelefono(int idtipotelefono) {
		this.idtipotelefono = idtipotelefono;
	}



	public String getNombretipotelefono() {
		return nombretipotelefono;
	}



	public void setNombretipotelefono(String nombretipotelefono) {
		this.nombretipotelefono = nombretipotelefono;
	}


	
	

}
