package proyecto.vo;

// Generated 13/10/2010 11:46:12 AM by Hibernate Tools 3.3.0.GA

import java.util.ArrayList;
import java.util.List;

/**
 * Tipoproyecto generated by hbm2java
 */
public class Tipoproyecto implements java.io.Serializable {

	private Integer idtipoproyecto;
	private String nombretipoproyecto;
	//private List<Proyecto> proyectos = new ArrayList<Proyecto>();

	public Tipoproyecto() {
		idtipoproyecto=new Integer(0);
		
	}

	public Tipoproyecto(String nombretipoproyecto, List<Proyecto> proyectos) {
		this.nombretipoproyecto = nombretipoproyecto;
		//this.proyectos = proyectos;
	}

	public Integer getIdtipoproyecto() {
		return this.idtipoproyecto;
	}

	public void setIdtipoproyecto(Integer idtipoproyecto) {
		this.idtipoproyecto = idtipoproyecto;
	}

	public String getNombretipoproyecto() {
		return this.nombretipoproyecto;
	}

	public void setNombretipoproyecto(String nombretipoproyecto) {
		this.nombretipoproyecto = nombretipoproyecto;
	}

	/*
	public List<Proyecto> getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(List<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}
*/
}
