package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

/**
 * Turismoatractivo generated by hbm2java
 */
public class Turismoatractivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idturismoatractivo;
	private Turismo turismo;
	private String tipoturismoatractivo;
	private String nombrezonaturismoatractivo;
	private String ubicacionturismoatractivo;
	private String imgturismoatractivo;

	public Turismoatractivo() {
	}

	public Turismoatractivo(Turismo turismo) {
		this.turismo = turismo;
	}

	public Turismoatractivo(Turismo turismo, String tipoturismoatractivo,
			String nombrezonaturismoatractivo,
			String ubicacionturismoatractivo, String imgturismoatractivo) {
		this.turismo = turismo;
		this.tipoturismoatractivo = tipoturismoatractivo;
		this.nombrezonaturismoatractivo = nombrezonaturismoatractivo;
		this.ubicacionturismoatractivo = ubicacionturismoatractivo;
		this.imgturismoatractivo = imgturismoatractivo;
	}

	public int getIdturismoatractivo() {
		return this.idturismoatractivo;
	}

	public void setIdturismoatractivo(int idturismoatractivo) {
		this.idturismoatractivo = idturismoatractivo;
	}

	public Turismo getTurismo() {
		return this.turismo;
	}

	public void setTurismo(Turismo turismo) {
		this.turismo = turismo;
	}

	public String getTipoturismoatractivo() {
		return this.tipoturismoatractivo;
	}

	public void setTipoturismoatractivo(String tipoturismoatractivo) {
		this.tipoturismoatractivo = tipoturismoatractivo;
	}

	public String getNombrezonaturismoatractivo() {
		return this.nombrezonaturismoatractivo;
	}

	public void setNombrezonaturismoatractivo(String nombrezonaturismoatractivo) {
		this.nombrezonaturismoatractivo = nombrezonaturismoatractivo;
	}

	public String getUbicacionturismoatractivo() {
		return this.ubicacionturismoatractivo;
	}

	public void setUbicacionturismoatractivo(String ubicacionturismoatractivo) {
		this.ubicacionturismoatractivo = ubicacionturismoatractivo;
	}

	public String getImgturismoatractivo() {
		return this.imgturismoatractivo;
	}

	public void setImgturismoatractivo(String imgturismoatractivo) {
		this.imgturismoatractivo = imgturismoatractivo;
	}

}
