package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA


/**
 * Turismo generated by hbm2java
 */
public class TurismoOperadorturismo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Turismo turismo;
	private Operadorturismo operadorturismo;

	public TurismoOperadorturismo() {
		turismo=new Turismo();
		operadorturismo=new Operadorturismo();
	}

	public Turismo getTurismo() {
		return turismo;
	}

	public void setTurismo(Turismo turismo) {
		this.turismo = turismo;
	}

	public Operadorturismo getOperadorturismo() {
		return operadorturismo;
	}

	public void setOperadorturismo(Operadorturismo operadorturismo) {
		this.operadorturismo = operadorturismo;
	}
	
	



	
	
	

	
}
