package proyecto.vo;

// Generated 14/10/2010 09:52:30 AM by Hibernate Tools 3.3.0.GA

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Turismo generated by hbm2java
 */
public class Turismo  extends Areanatural  implements Serializable {

	private int idturismo;
	//private Areanatural areanatural;
	

	public Turismo() {
		super();
	}

	
	public Turismo(int idturismo) {
		this();
		this.idturismo=idturismo; 
	}
	
	

	public int getIdturismo() {
		return this.idturismo;
	}

	public void setIdturismo(int idturismo) {
		this.idturismo = idturismo;
	}

	
	

}
