Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (1, 11.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (2, 10.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (3, 9.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (4, 8.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (5, 7.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (6, 6.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (7, 5.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (8, 4.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (9, 3.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (10, 2.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (11, 1.5, 12);
Insert into TRON2000.TA_MESES_RENT_PESO
   (NUM_MES, MESES_RENTABLES, TOTAL_MESES)
 Values
   (12, 0.5, 12);
COMMIT;
