/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 21:33:30
*/

Ext.define('MyApp.view.GestionarUsuario.UsuarioPerfilSubCrudEdit', {
    extend: 'Ext.window.Window',
    alias : 'widget.UsuarioPerfilSubCrudEdit',

    requires: ['Ext.form.Panel'],

    layout: 'fit',
    autoShow: true,
    modal: true,
    floating: true,
    resizable: false,
    width: 350,
    
    glyph:'xf044@FontAwesome',

    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                id: 'form_submodel_UsuarioPerfilSubCrud',
                padding: '5 5 0 5',
                border: false,
                style: 'background-color: #fff;',
                
                fieldDefaults: {
                    anchor: '100%',
                    labelAlign: 'left',
                    allowBlank: false,
                    combineErrors: true,
                    msgTarget: 'qtip',
                    labelWidth: 125
                },

                items: [
					{
					    readOnly : false,
						allowBlank : true,
						hidden : true,
						xtype : 'textfield',
						name : 'id_usuario',
						fieldLabel : 'id_usuario',
						disabled : false,
						editable : true
					}
					,{
					    readOnly : false,
						store : {
								fields: ['id_perfil','nombre_perfil'],
								proxy: {
							         type: 'ajax',
							         url: '/SeguridadWSRestApp/api/seguridad/perfilPorNombre',
							         reader: {
							             type: 'json',
							             rootProperty: 'list'
							         }
						    	},
								autoLoad: true
					    },
						queryMode : 'local',
						displayField : 'nombre_perfil',
						hidden : false,
						xtype : 'combobox',
						name : 'id_perfil',
						valueField : 'id_perfil',
						emptyText : '-- Seleccione Opción --',
						fieldLabel : 'Perfil',
						disabled : false,
						editable : true
					}
					,{
					    readOnly : false,
						store : {
								fields: ['valor_item','descrip_item'],
								proxy: {
							         type: 'ajax',
							         url: '/SeguridadWSRestApp/api/catalogo/buscarPorNombre?nombre_catalogo=estado_generico',
							         reader: {
							             type: 'json',
							             rootProperty: 'list'
							         }
						    	},
								autoLoad: true
					    },
						queryMode : 'local',
						displayField : 'descrip_item',
						hidden : false,
						xtype : 'combobox',
						name : 'id_estado',
						valueField : 'valor_item',
						emptyText : '-- Seleccione Opción --',
						fieldLabel : 'Estado',
						disabled : false,
						editable : false
					}
                ]
            }
        ];
        
        this.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            //id:'buttons_UsuarioPerfilSubCrud',
            ui: 'footer',
            items: ['->', {
            	glyph:'xf0c7@FontAwesome',
                itemId: 'save',
                text: 'Grabar',
                action: 'save'
            },{
            	glyph:'xf00d@FontAwesome',
                text: 'Cancelar',
                scope: this,
                handler: this.close
            }]
        }];

        this.callParent(arguments);
    }
});
