/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   14/09/2016 05:45:45
*/

Ext.define('MyApp.view.GestionarDocFactura.Filter', {

    extend: 'Ext.form.Panel',
    alias: 'widget.GestionarDocFacturaFilter',
    requires: ['Ext.form.Panel'],
    
    id:'form_filter_GestionarDocFactura',
	layout: {
        type: 'vbox'
    },
    fieldDefaults: {
        labelAlign: 'top',
        margin: "0 5 5 5"
    },
                                
    initComponent: function() {
    
    	var form = this;
    
        this.items = [
                {
                	xtype: 'container',
                	layout: {
                		type: 'hbox',
                		align: 'stretch'
                	},
                	items: [
							{
								xtype : 'numberfield',
								hidden : false,
								editable : true,
								fieldLabel : 'Año',
								name : 'anio_emision',
								disabled : false
							}
							,{
								xtype : 'numberfield',
								hidden : false,
								editable : true,
								fieldLabel : 'Mes',
								name : 'mes_emision',
								disabled : false
							}
							,{
								xtype : 'numberfield',
								hidden : false,
								editable : true,
								fieldLabel : 'Dia',
								name : 'dia_emision',
								disabled : false
							}
							,{
								xtype : 'numberfield',
								hidden : false,
								editable : true,
								fieldLabel : 'Numero Factura',
								name : 'num_docu_venta',
								disabled : false
							}
							,{
								xtype : 'textfield',
								hidden : false,
								editable : true,
								fieldLabel : 'Cliente',
								name : 'nombres_cliente',
								disabled : false
							}
						]
					}
        ];

        this.callParent(arguments);
    }
});