/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   14/09/2016 05:45:45
*/

Ext.define('MyApp.view.GestionarDocFactura.List' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.GestionarDocFacturaList',
    
    requires: ['MyApp.view.GestionarDocFactura.Filter'],

    glyph:'xf022@FontAwesome',

    title : 'Gestionar Facturas',
    store: 'GestionarDocFactura.MainStore',

    columns: [
		{
	    	header: "id_documento_venta",
			flex:115 / 100,
			dataIndex: 'id_documento_venta',
			hidden:true,
			sortable:true
		}
		,{
			header: "id_tipo_documento_venta",
			flex:115 / 100,
			dataIndex: 'id_tipo_documento_venta',
			hidden:true,
			sortable:true
		}
		,{
			header: "Fecha Emisión",
			flex:115 / 100,
			dataIndex: 'fecha_emision',
			hidden:false,
			sortable:true
		}
		,{
			header: "Fecha Cancelado",
			flex:115 / 100,
			dataIndex: 'fecha_cancelado',
			hidden:false,
			sortable:true
		}
		,{
			header: "Numero Documento",
			flex:115 / 100,
			dataIndex: 'serie_num_doc',
			hidden:false,
			sortable:true
		}
		,{
			header: "Cliente",
			flex:115 / 100,
			dataIndex: 'nombres_cliente',
			hidden:false,
			sortable:true
		}
		,{
			header: "Tipo documento",
			flex:115 / 100,
			dataIndex: 'descrip_tipo_docu_cliente',
			hidden:false,
			sortable:true
		}
		,{
			header: "Numero documento",
			flex:115 / 100,
			dataIndex: 'num_docu_cliente',
			hidden:false,
			sortable:true
		}
		,{
			header: "Numero guia remisión",
			flex:115 / 100,
			dataIndex: 'num_guia_remision',
			hidden:false,
			sortable:true
		}
		,{
			header: "Sub total",
			flex:115 / 100,
			dataIndex: 'sub_total_venta',
			hidden:false,
			sortable:true
		}
		,{
			header: "IGV",
			flex:115 / 100,
			dataIndex: 'valor_igv_venta',
			hidden:false,
			sortable:true
		}
		,{
			header: "Importe Total",
			flex:115 / 100,
			dataIndex: 'importe_total',
			hidden:false,
			sortable:true
		}
		,{
			header: "Recibe percepción?",
			flex:115 / 100,
			dataIndex: 'descrip_flag_percepcion',
			hidden:false,
			sortable:true
		}
		,{
			header: "Porcentaje percepción",
			flex:115 / 100,
			dataIndex: 'percentage_percepcion',
			hidden:false,
			sortable:true
		}
		,{
			header: "Monto percepción",
			flex:115 / 100,
			dataIndex: 'monto_percepcion',
			hidden:false,
			sortable:true
		}
		,{
			header: "Estado",
			flex:115 / 100,
			dataIndex: 'descrip_estado',
			hidden:false,
			sortable:true
		}
		,{
			header: "Fecha Registro",
			flex:115 / 100,
			dataIndex: 'fecha_registro',
			hidden:false,
			sortable:true
		}
	],
	
	initComponent: function() {
		
		this.dockedItems = [
		     {
		          xtype: 'GestionarDocFacturaFilter'
		     },
			 {
	            xtype: 'toolbar',
	            items: [
				            {
				            	glyph:'xf0b0@FontAwesome',
				                text: 'Filtrar',
				                action: 'filter'
				            },
				            '-',
				            {
				            	glyph:'xf12d@FontAwesome',
				                text: 'Limpiar',
				                action: 'clearFilter'
				            },
				            '-',
				            {
				            	glyph:'xf055@FontAwesome',
				                text: 'Agregar',
				                action: 'add'
				            },
				            '-',
				            {
				            	glyph:'xf056@FontAwesome',
				                text: 'Eliminar',
				                action: 'delete'
				            }
			           ]
	        },
	        {
	            xtype: 'pagingtoolbar',
	            dock:'top',
	            store: 'GestionarDocFactura.MainStore',
	            displayInfo: true
	        }
        ];
		
		this.callParent(arguments);
        this.on('render', this.loadStore, this);
	},
    loadStore: function() {
        this.getStore().load();
    }
});
