/*
* Copyright «©» 2017, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The CustomerMailQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   06/02/2017 22:14:49
*/

package pe.kapcom.iemail.repository.dto; 

public class CustomerMailQuery implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String tipdoc_id; 
	private String vcab_nrodoc; 
	private String tip; 
	private String nro_doc; 
	private java.util.Date fec_emision; 
	private java.util.Date fec_envio; 
	private String cli_razsoc; 
	private String doc_iden; 
	private String mail; 
	private String ruta; 


	public String getTipdoc_id() { 
	  return tipdoc_id; 
	} 
	public void setTipdoc_id(String tipdoc_id) { 
	  this.tipdoc_id = tipdoc_id; 
	} 
	public String getVcab_nrodoc() { 
	  return vcab_nrodoc; 
	} 
	public void setVcab_nrodoc(String vcab_nrodoc) { 
	  this.vcab_nrodoc = vcab_nrodoc; 
	} 
	public String getTip() { 
	  return tip; 
	} 
	public void setTip(String tip) { 
	  this.tip = tip; 
	} 
	public String getNro_doc() { 
	  return nro_doc; 
	} 
	public void setNro_doc(String nro_doc) { 
	  this.nro_doc = nro_doc; 
	} 
	public java.util.Date getFec_emision() { 
	  return fec_emision; 
	} 
	public void setFec_emision(java.util.Date fec_emision) { 
	  this.fec_emision = fec_emision; 
	} 
	public java.util.Date getFec_envio() { 
	  return fec_envio; 
	} 
	public void setFec_envio(java.util.Date fec_envio) { 
	  this.fec_envio = fec_envio; 
	} 
	public String getCli_razsoc() { 
	  return cli_razsoc; 
	} 
	public void setCli_razsoc(String cli_razsoc) { 
	  this.cli_razsoc = cli_razsoc; 
	} 
	public String getDoc_iden() { 
	  return doc_iden; 
	} 
	public void setDoc_iden(String doc_iden) { 
	  this.doc_iden = doc_iden; 
	} 
	public String getMail() { 
	  return mail; 
	} 
	public void setMail(String mail) { 
	  this.mail = mail; 
	} 
	public String getRuta() { 
	  return ruta; 
	} 
	public void setRuta(String ruta) { 
	  this.ruta = ruta; 
	} 


} 