/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   28/02/2016 02:49:06
*/

Ext.define('MyApp.view.GestionarFuncionalidad.List' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.GestionarFuncionalidadList',
    
    requires: ['MyApp.view.GestionarFuncionalidad.Filter'],

    glyph:'xf022@FontAwesome',

    title : 'Gestionar Funcionalidades',
    store: 'GestionarFuncionalidad.MainStore',

    columns: [
		{
	    	header: "Id Funcionalidad",
			flex:115 / 100,
			dataIndex: 'id_funcionalidad',
			hidden:false,
			sortable:true
		}
		,{
			header: "Nombre",
			flex:115 / 100,
			dataIndex: 'nombre_funcionalidad',
			hidden:false,
			sortable:true
		}
		,{
			header: "Recurso",
			flex:115 / 100,
			dataIndex: 'recurso_funcionalidad',
			hidden:false,
			sortable:true
		}
		,{
			header: "Icon Class Css",
			flex:115 / 100,
			dataIndex: 'icon_cls',
			hidden:false,
			sortable:true
		}
		,{
			header: "Alias Component ExtJs",
			flex:115 / 100,
			dataIndex: 'alias_component',
			hidden:false,
			sortable:true
		}
		,{
			header: "Controllers",
			flex:115 / 100,
			dataIndex: 'component_controllers',
			hidden:false,
			sortable:true
		}
		,{
			header: "Estado",
			flex:115 / 100,
			dataIndex: 'descrip_estado',
			hidden:false,
			sortable:true
		}
		,{
			header: "F. Registro",
			flex:115 / 100,
			dataIndex: 'fecha_registro',
			hidden:false,
			sortable:true
		}
	],
	
	initComponent: function() {
		
		this.dockedItems = [
		     {
		          xtype: 'GestionarFuncionalidadFilter'
		     },
			 {
	            xtype: 'toolbar',
	            items: [
				            {
				            	glyph:'xf0b0@FontAwesome',
				                text: 'Filtrar',
				                action: 'filter'
				            },
				            '-',
				            {
				            	glyph:'xf12d@FontAwesome',
				                text: 'Limpiar',
				                action: 'clearFilter'
				            },
				            '-',
				            {
				            	glyph:'xf055@FontAwesome',
				                text: 'Agregar',
				                action: 'add'
				            },
				            '-',
				            {
				            	glyph:'xf056@FontAwesome',
				                text: 'Eliminar',
				                action: 'delete'
				            }
			           ]
	        },
	        {
	            xtype: 'pagingtoolbar',
	            dock:'top',
	            store: 'GestionarFuncionalidad.MainStore',
	            displayInfo: true
	        }
        ];
		
		this.callParent(arguments);
        this.on('render', this.loadStore, this);
	},
    loadStore: function() {
        this.getStore().load();
    }
});
