/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The SaldoQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   15/03/2016 00:45:25
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.SaldoQuery;
import pe.com.acme.query.mybatis.model.SaldoQueryCriteria;

public interface SaldoQueryMapper { 
   List<SaldoQuery> getListQueryByCriteria(SaldoQueryCriteria criteria);
   List<SaldoQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<SaldoQuery> getListQueryPaginationByCriteria(SaldoQueryCriteria criteria, RowBounds rowBounds); 
   List<SaldoQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(SaldoQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
