/*
* Copyright «©» 2017, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The ResumenPagosPorFechaQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   27/03/2017 20:05:40
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.ResumenPagosPorFechaQuery;
import pe.com.acme.query.mybatis.model.ResumenPagosPorFechaQueryCriteria;

public interface ResumenPagosPorFechaQueryMapper { 
   List<ResumenPagosPorFechaQuery> getListQueryByCriteria(ResumenPagosPorFechaQueryCriteria criteria);
   List<ResumenPagosPorFechaQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<ResumenPagosPorFechaQuery> getListQueryPaginationByCriteria(ResumenPagosPorFechaQueryCriteria criteria, RowBounds rowBounds); 
   List<ResumenPagosPorFechaQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(ResumenPagosPorFechaQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
