/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The UsuarioRolCrudCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   27/02/2016 13:54:15
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModelCriteria;

public class UsuarioRolCrudCriteria extends AbstractModelCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private String nombre_usuario; 
	private Integer id_aplicacion; 
	private Integer id_rol; 
	private Integer id_estado; 

	public UsuarioRolCrudCriteria() {
		super();
	}
	
	public String getNombre_usuario() { 
	  return nombre_usuario; 
	} 
	public void setNombre_usuario(String nombre_usuario) { 
	  this.nombre_usuario = nombre_usuario; 
	} 
	public Integer getId_aplicacion() { 
	  return id_aplicacion; 
	} 
	public void setId_aplicacion(Integer id_aplicacion) { 
	  this.id_aplicacion = id_aplicacion; 
	} 
	public Integer getId_rol() { 
	  return id_rol; 
	} 
	public void setId_rol(Integer id_rol) { 
	  this.id_rol = id_rol; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 

} 