/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The UsuarioPerfilSubCrudCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 19:46:43
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModelCriteria;

public class UsuarioPerfilSubCrudCriteria extends AbstractModelCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_usuario; 

	public UsuarioPerfilSubCrudCriteria() {
		super();
	}
	
	public Integer getId_usuario() { 
	  return id_usuario; 
	} 
	public void setId_usuario(Integer id_usuario) { 
	  this.id_usuario = id_usuario; 
	} 

} 