/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   29/03/2016 22:54:29
*/

Ext.define('MyApp.view.Statistic.CharactersOnlineList' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.CharactersOnlineList',
    
    iconCls:'icon-world_connect',

    title : 'Characters Online',
    
    store : Ext.create('Ext.data.Store',{
    	
    	fields: [
    	         {name: 'memb___id', type: 'string'},
    	         {name: 'gameIDC', type: 'string'},
    	         {name: 'descrip_clazz', type: 'string'},
    	         {name: 'cLevel', type: 'integer'},
    	         {name: 'resets', type: 'integer'},
    	         {name: 'mapNumber', type: 'integer'},
    	         {name: 'descrip_map', type: 'string'},
    	         {name: 'mapPosX', type: 'integer'},
    	         {name: 'mapPosY', type: 'integer'},
    	         {name: 'CtlCode', type: 'integer'},
    	         {name: 'descrip_CtlCode', type: 'string'}
    	        ],
    	        
    	proxy: {
    		type: 'ajax',
    		url: '/MuWSRestApp/api/Statistic/charactersOnline',
            reader: {
                type: 'json',
                rootProperty: 'data',
                successProperty: 'success',
                totalProperty: 'total',
                messageProperty: 'message'
            }
    	},
    	
    	autoLoad: false
    }),

    columns: [

		{
			header: "Character",
			flex:1,
			dataIndex: 'gameIDC',
			hidden:false,
			sortable:false
		},
		{
			header: "Class",
			flex:1,
			dataIndex: 'descrip_clazz',
			hidden:false,
			sortable:false
		},
		{
			header: "Level",
			flex:1,
			dataIndex: 'cLevel',
			hidden:false,
			sortable:false
		},
		{
			header: "Resets",
			flex:1,
			dataIndex: 'resets',
			hidden:false,
			sortable:false
		}
		,{
			header: "Map",
			flex:1,
			dataIndex: 'descrip_map',
			hidden:false,
			sortable:false
		}
		,{
			header: "Map Pos X",
			flex:1,
			dataIndex: 'mapPosX',
			hidden:false,
			sortable:false
		}
		,{
			header: "Map Pos Y",
			flex:1,
			dataIndex: 'mapPosY',
			hidden:false,
			sortable:false
		},
		{
			header: "Type",
			flex:1,
			dataIndex: 'descrip_CtlCode',
			hidden:false,
			sortable:false
		}
		
	],
	
	initComponent: function() {
		
		var me = this;
		
		this.dockedItems = [
			 {
	            xtype: 'pagingtoolbar',
	            dock:'top',
	            store : me.store,
	            displayInfo: true
	        }
        ];
		
		this.callParent(arguments);
		this.on('render', this.loadStore, this);
	},
    loadStore: function() {
        this.getStore().load();
    }
});
