      CREATE INDEX TB_CUSTOMER_CUSTOMERCODE_IDX ON TB_CUSTOMER (CUSTOMERCODE);
      CREATE INDEX TB_DELIVERY_CUSTOMERCODE_IDX ON TB_DELIVERY_ADDRESS (CUSTOMERCODE);
      CREATE INDEX TB_DELIVERY_ZONECODE_IDX ON TB_DELIVERY_ADDRESS (ZONECODE);
      CREATE INDEX TB_ZONE_ZONECODE_IDX ON TB_ZONE (ZONECODE);