/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuiaPorJornadaClienteQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   16/03/2016 18:45:19
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class GuiaPorJornadaClienteQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia; 
	private Integer id_cliente; 
	private java.util.Date fecha_jornada; 
	private Integer id_estado; 


	public Integer getId_guia() { 
	  return id_guia; 
	} 
	public void setId_guia(Integer id_guia) { 
	  this.id_guia = id_guia; 
	} 
	public Integer getId_cliente() { 
	  return id_cliente; 
	} 
	public void setId_cliente(Integer id_cliente) { 
	  this.id_cliente = id_cliente; 
	} 
	public java.util.Date getFecha_jornada() { 
	  return fecha_jornada; 
	} 
	public void setFecha_jornada(java.util.Date fecha_jornada) { 
	  this.fecha_jornada = fecha_jornada; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 


} 