/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuiaPesoQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   12/03/2016 02:17:53
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class GuiaPesoQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia_peso; 
	private Integer id_guia; 
	private Integer flag_devolucion;
	private Integer id_tipo_peso; 
	private String descrip_tipo_peso; 
	private Integer num_jabas; 
	private Integer num_aves; 
	private Double peso_obtenido; 
	private Integer id_estado; 
	private String descrip_estado; 


	public Integer getId_guia_peso() { 
	  return id_guia_peso; 
	} 
	public void setId_guia_peso(Integer id_guia_peso) { 
	  this.id_guia_peso = id_guia_peso; 
	} 
	public Integer getId_guia() { 
	  return id_guia; 
	} 
	public void setId_guia(Integer id_guia) { 
	  this.id_guia = id_guia; 
	} 
	public Integer getId_tipo_peso() { 
	  return id_tipo_peso; 
	} 
	public void setId_tipo_peso(Integer id_tipo_peso) { 
	  this.id_tipo_peso = id_tipo_peso; 
	} 
	public String getDescrip_tipo_peso() { 
	  return descrip_tipo_peso; 
	} 
	public void setDescrip_tipo_peso(String descrip_tipo_peso) { 
	  this.descrip_tipo_peso = descrip_tipo_peso; 
	} 
	public Integer getNum_jabas() { 
	  return num_jabas; 
	} 
	public void setNum_jabas(Integer num_jabas) { 
	  this.num_jabas = num_jabas; 
	} 
	public Integer getNum_aves() { 
	  return num_aves; 
	} 
	public void setNum_aves(Integer num_aves) { 
	  this.num_aves = num_aves; 
	} 
	public Double getPeso_obtenido() { 
	  return peso_obtenido; 
	} 
	public void setPeso_obtenido(Double peso_obtenido) { 
	  this.peso_obtenido = peso_obtenido; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 
	public String getDescrip_estado() { 
	  return descrip_estado; 
	} 
	public void setDescrip_estado(String descrip_estado) { 
	  this.descrip_estado = descrip_estado; 
	}
	public Integer getFlag_devolucion() {
		return flag_devolucion;
	}
	public void setFlag_devolucion(Integer flag_devolucion) {
		this.flag_devolucion = flag_devolucion;
	} 


} 