/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The GuiaCompraQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   13/03/2016 15:48:33
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class GuiaCompraQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_guia; 
	private Integer num_anio; 
	private Integer num_mes; 
	private Integer num_dia; 
	private Integer id_tipo_guia;
	private String descrip_tipo_guia;
	private Integer id_guia_referencia;
	private String cod_jornada; 
	private String fecha_jornada; 
	private Integer id_tipo_producto; 
	private String descrip_tipo_producto; 
	private Integer id_proveedor; 
	private String nombre_proveedor; 
	private Double total_peso_bruto; 
	private Double total_peso_tara; 
	private Double total_peso_devolucion; 
	private Double total_peso_neto; 
	private Double precio_aplicado; 
	private Double total_importe; 
	private Integer id_estado; 
	private String descrip_estado; 

	private java.util.List<GuiaPesoQuery> listGuiaPesoQuery; 

	public Integer getId_guia() { 
	  return id_guia; 
	} 
	public void setId_guia(Integer id_guia) { 
	  this.id_guia = id_guia; 
	} 
	public Integer getNum_anio() { 
	  return num_anio; 
	} 
	public void setNum_anio(Integer num_anio) { 
	  this.num_anio = num_anio; 
	} 
	public Integer getNum_mes() { 
	  return num_mes; 
	} 
	public void setNum_mes(Integer num_mes) { 
	  this.num_mes = num_mes; 
	} 
	public Integer getNum_dia() { 
	  return num_dia; 
	} 
	public void setNum_dia(Integer num_dia) { 
	  this.num_dia = num_dia; 
	} 
	public String getCod_jornada() { 
	  return cod_jornada; 
	} 
	public void setCod_jornada(String cod_jornada) { 
	  this.cod_jornada = cod_jornada; 
	} 
	public String getFecha_jornada() { 
	  return fecha_jornada; 
	} 
	public void setFecha_jornada(String fecha_jornada) { 
	  this.fecha_jornada = fecha_jornada; 
	} 
	public Integer getId_tipo_producto() { 
	  return id_tipo_producto; 
	} 
	public void setId_tipo_producto(Integer id_tipo_producto) { 
	  this.id_tipo_producto = id_tipo_producto; 
	} 
	public String getDescrip_tipo_producto() { 
	  return descrip_tipo_producto; 
	} 
	public void setDescrip_tipo_producto(String descrip_tipo_producto) { 
	  this.descrip_tipo_producto = descrip_tipo_producto; 
	} 
	public Integer getId_proveedor() { 
	  return id_proveedor; 
	} 
	public void setId_proveedor(Integer id_proveedor) { 
	  this.id_proveedor = id_proveedor; 
	} 
	public String getNombre_proveedor() { 
	  return nombre_proveedor; 
	} 
	public void setNombre_proveedor(String nombre_proveedor) { 
	  this.nombre_proveedor = nombre_proveedor; 
	} 
	public Double getTotal_peso_bruto() { 
	  return total_peso_bruto; 
	} 
	public void setTotal_peso_bruto(Double total_peso_bruto) { 
	  this.total_peso_bruto = total_peso_bruto; 
	} 
	public Double getTotal_peso_tara() { 
	  return total_peso_tara; 
	} 
	public void setTotal_peso_tara(Double total_peso_tara) { 
	  this.total_peso_tara = total_peso_tara; 
	} 
	public Double getTotal_peso_devolucion() { 
	  return total_peso_devolucion; 
	} 
	public void setTotal_peso_devolucion(Double total_peso_devolucion) { 
	  this.total_peso_devolucion = total_peso_devolucion; 
	} 
	public Double getTotal_peso_neto() { 
	  return total_peso_neto; 
	} 
	public void setTotal_peso_neto(Double total_peso_neto) { 
	  this.total_peso_neto = total_peso_neto; 
	} 
	public Double getPrecio_aplicado() { 
	  return precio_aplicado; 
	} 
	public void setPrecio_aplicado(Double precio_aplicado) { 
	  this.precio_aplicado = precio_aplicado; 
	} 
	public Double getTotal_importe() { 
	  return total_importe; 
	} 
	public void setTotal_importe(Double total_importe) { 
	  this.total_importe = total_importe; 
	} 
	public Integer getId_estado() { 
	  return id_estado; 
	} 
	public void setId_estado(Integer id_estado) { 
	  this.id_estado = id_estado; 
	} 
	public String getDescrip_estado() { 
	  return descrip_estado; 
	} 
	public void setDescrip_estado(String descrip_estado) { 
	  this.descrip_estado = descrip_estado; 
	} 

	public java.util.List<GuiaPesoQuery> getListGuiaPesoQuery() { 
	  return listGuiaPesoQuery; 
	} 
	public void setListGuiaPesoQuery(java.util.List<GuiaPesoQuery> listGuiaPesoQuery) { 
	  this.listGuiaPesoQuery = listGuiaPesoQuery; 
	}
	public Integer getId_tipo_guia() {
		return id_tipo_guia;
	}
	public void setId_tipo_guia(Integer id_tipo_guia) {
		this.id_tipo_guia = id_tipo_guia;
	}
	public Integer getId_guia_referencia() {
		return id_guia_referencia;
	}
	public void setId_guia_referencia(Integer id_guia_referencia) {
		this.id_guia_referencia = id_guia_referencia;
	}
	public String getDescrip_tipo_guia() {
		return descrip_tipo_guia;
	}
	public void setDescrip_tipo_guia(String descrip_tipo_guia) {
		this.descrip_tipo_guia = descrip_tipo_guia;
	} 

} 