/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The ObtenerNumDocVentaQuery class is the resultset equivalent of an SQL query
* for Java and will be managed by Mybatis.
*
* @author  Javier Raffo
* @version 1.0
* @since   16/09/2016 06:22:41
*/

package pe.com.acme.query.mybatis.model; 

import pe.com.acme.util.AbstractModel;

public class ObtenerNumDocVentaQuery extends AbstractModel implements java.io.Serializable { 

	private static final long serialVersionUID = 1L;
	
	private Integer id_serie_numero_doc; 
	private Integer longitud; 
	private Integer numero_doc; 


	public Integer getId_serie_numero_doc() { 
	  return id_serie_numero_doc; 
	} 
	public void setId_serie_numero_doc(Integer id_serie_numero_doc) { 
	  this.id_serie_numero_doc = id_serie_numero_doc; 
	} 
	public Integer getLongitud() { 
	  return longitud; 
	} 
	public void setLongitud(Integer longitud) { 
	  this.longitud = longitud; 
	} 
	public Integer getNumero_doc() { 
	  return numero_doc; 
	} 
	public void setNumero_doc(Integer numero_doc) { 
	  this.numero_doc = numero_doc; 
	} 


} 