/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The FacturaWebQueryCriteria class conten the params in shape attributes 
* equivalents of an clause WHERE for SQL query.
*
* @author  Javier Raffo
* @version 1.0
* @since   19/07/2016 04:56:06
*/

package pe.com.acme.invoiceelec.model.mybatis.query.dto; 

import pe.com.acme.util.AbstractModelCriteria;

public class FacturaWebQueryCriteria extends AbstractModelCriteria implements java.io.Serializable  { 

	private static final long serialVersionUID = 1L;
	
	private Integer fechaemisanio; 
	private Integer fechaemismes; 
	private Integer fechaemisdia; 
	private String tipodocumentousuario; 
	private String numerodocumentousuario; 
	private Integer numerodocumento; 
	private Integer numf_correl; 

	public FacturaWebQueryCriteria() {
		super();
	}
	
	public Integer getFechaemisanio() { 
	  return fechaemisanio; 
	} 
	public void setFechaemisanio(Integer fechaemisanio) { 
	  this.fechaemisanio = fechaemisanio; 
	} 
	public Integer getFechaemismes() { 
	  return fechaemismes; 
	} 
	public void setFechaemismes(Integer fechaemismes) { 
	  this.fechaemismes = fechaemismes; 
	} 
	public Integer getFechaemisdia() { 
	  return fechaemisdia; 
	} 
	public void setFechaemisdia(Integer fechaemisdia) { 
	  this.fechaemisdia = fechaemisdia; 
	} 
	public String getTipodocumentousuario() { 
	  return tipodocumentousuario; 
	} 
	public void setTipodocumentousuario(String tipodocumentousuario) { 
	  this.tipodocumentousuario = tipodocumentousuario; 
	} 
	public String getNumerodocumentousuario() { 
	  return numerodocumentousuario; 
	} 
	public void setNumerodocumentousuario(String numerodocumentousuario) { 
	  this.numerodocumentousuario = numerodocumentousuario; 
	} 
	public Integer getNumerodocumento() { 
	  return numerodocumento; 
	} 
	public void setNumerodocumento(Integer numerodocumento) { 
	  this.numerodocumento = numerodocumento; 
	} 
	public Integer getNumf_correl() { 
	  return numf_correl; 
	} 
	public void setNumf_correl(Integer numf_correl) { 
	  this.numf_correl = numf_correl; 
	} 

} 