/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   17/03/2016 17:34:43
*/

Ext.define('MyApp.controller.GestionarSaldo.GuiaSaldoQueryController', {
    extend: 'Ext.app.Controller',

    stores: ['GestionarSaldo.GuiaSaldoQueryStore'],

    models: ['GestionarSaldo.GuiaSaldoQueryModel'],

    views: ['GestionarSaldo.GuiaSaldoQueryEdit', 'GestionarSaldo.GuiaSaldoQueryList'],

    refs: [
    	{
            ref: 'GuiaSaldoQueryPanel',
            selector: 'panel'
        },
        {
            ref: 'GuiaSaldoQueryList',
            selector: 'GuiaSaldoQueryList'
        }
    ],

    init: function() {
        this.control({
            'GuiaSaldoQueryList dataview': {
                itemdblclick: this.editRecord
            },
            'GuiaSaldoQueryList button[action=add]': {
            	click: this.editRecord
            },
            'GuiaSaldoQueryList button[action=delete]': {
                click: this.deleteRecord
            },
            'GuiaSaldoQueryEdit button[action=save]': {
                click: this.updateRecord
            }
        });
    },

    editRecord: function(grid, record) {
        var edit = Ext.create('MyApp.view.GestionarSaldo.GuiaSaldoQueryEdit').show();
        var form = edit.down('form');
        
        if(record.data){
        	edit.down('form').loadRecord(record);
        	edit.setTitle('Editar');
        }else{
        	edit.setTitle('Agregar');
        	
          	var id_estado = form.getForm().findField('id_estado');
          	id_estado.setReadOnly(true);
          	id_estado.setValue(1);
        }
    },
    
    updateRecord: function(button) {
    	
        var win = button.up('window');
        var form = win.down('form');
        var record = form.getRecord();
        var values = form.getValues();
        var store = Ext.getStore('GestionarSaldo.GuiaSaldoQueryStore');
        
        
        if (form.isValid()) {
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de GRABAR el registro?',function (btn) {
	            
	            if (btn == 'yes') {
                
                    if(win.title === 'Editar') {
                        record.set(values);
                    } else{
                        record = Ext.create('MyApp.model.GestionarSaldo.GuiaSaldoQueryModel');
                        record.set(values);
                        store.add(record);
                    }

                   	
                    store.sync({
                        success: function (batch, eOpts) {
                            store.load({params: {id_guia: null}});
                            win.close();
                        },
	        	        failure: function (batch, eOpts) {
							store.rejectChanges();
	        	        }
                    });
	            }
	            
	     });
        
        }
    },
    deleteRecord: function(button) {
    	
    	var grid = this.getGuiaSaldoQueryList();
    	var record = grid.getSelectionModel().getSelection(); 
    	var store = Ext.getStore('GestionarSaldo.GuiaSaldoQueryStore');
    	
    	if(record.length > 0){
	        Ext.Msg.confirm('Confirmar','¿Estás seguro de ELIMINAR el registro?',function (btn) {
	                if (btn == 'yes') {
	             	   store.remove(record);
						store.sync({
					        success: function (batch, eOpts) {
					            store.load({params: {id_guia: null}});
					        }
					    });
	                }
	        });
    	}

    }
    
});