/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 20:07:02
*/

package pe.com.acme.seguridad.business.service;

import java.util.List;
import pe.com.acme.query.mybatis.model.AplicacionCrud;
import pe.com.acme.query.mybatis.model.AplicacionCrudCriteria;
import pe.com.acme.util.IMybatisRepositoryHelper;

public interface GestionarAplicacionService extends IMybatisRepositoryHelper {
    Integer create(AplicacionCrud model) throws Exception;
    void update(AplicacionCrud model) throws Exception;
    void destroy(AplicacionCrud model) throws Exception;
    List<AplicacionCrud> list(AplicacionCrudCriteria criteria) throws Exception;
    int countRecords(AplicacionCrudCriteria criteria) throws Exception;
}