/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 19:52:17
*/

package pe.com.acme.seguridad.business.service;

import java.util.List;
import pe.com.acme.query.mybatis.model.UsuarioCrud;
import pe.com.acme.query.mybatis.model.UsuarioCrudCriteria;
import pe.com.acme.util.IMybatisRepositoryHelper;

public interface GestionarUsuarioService extends IMybatisRepositoryHelper {
    Integer create(UsuarioCrud model) throws Exception;
    void update(UsuarioCrud model) throws Exception;
    void destroy(UsuarioCrud model) throws Exception;
    List<UsuarioCrud> list(UsuarioCrudCriteria criteria) throws Exception;
    int countRecords(UsuarioCrudCriteria criteria) throws Exception;
}