/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   26/02/2016 18:07:06
*/

package pe.com.acme.seguridad.business.service;

import java.util.List;
import pe.com.acme.query.mybatis.model.PerfilCrud;
import pe.com.acme.query.mybatis.model.PerfilCrudCriteria;
import pe.com.acme.util.IMybatisRepositoryHelper;

public interface GestionarPerfilService extends IMybatisRepositoryHelper {
    Integer create(PerfilCrud model) throws Exception;
    void update(PerfilCrud model) throws Exception;
    void destroy(PerfilCrud model) throws Exception;
    List<PerfilCrud> list(PerfilCrudCriteria criteria) throws Exception;
    int countRecords(PerfilCrudCriteria criteria) throws Exception;
}