INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (1, 'Afghanistan', '293141');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (2, 'Albania', '553524');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (3, 'Algeria', '727298');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (4, 'Andorra', '804756');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (5, 'Angola', '376164');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (6, 'Antigua and Barbuda', '366907');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (7, 'Argentina', '316613');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (8, 'Armenia', '816466');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (9, 'Australia', '410238');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (10, 'Austria', '894267');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (11, 'Azerbaijan', '815701');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (12, 'Bahamas', '610438');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (13, 'Bahrain', '908482');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (14, 'Bangladesh', '164149');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (15, 'Barbados', '793231');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (16, 'Belarus', '591765');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (17, 'Belgium', '223516');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (18, 'Belize', '958196');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (19, 'Benin', '978371');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (20, 'Bhutan', '733443');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (21, 'Bolivia', '596856');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (22, 'Bosnia and Herzegovina', '440752');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (23, 'Botswana', '803991');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (24, 'Brazil', '576364');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (25, 'Brunei', '381122');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (26, 'Bulgaria', '529261');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (27, 'Burkina Faso', '135060');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (28, 'Burundi', '957721');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (29, 'Cambodia', '953633');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (30, 'Cameroon', '980666');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (31, 'Canada', '132844');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (32, 'Cape Verde', '554210');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (33, 'Central African Republic', '667008');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (34, 'Chad', '255612');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (35, 'Chile', '662314');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (36, 'China', '203024');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (37, 'Colombia', '898566');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (38, 'Comoros', '703641');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (39, 'Congo (Brazzaville)', '292139');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (40, 'Congo, Democratic Republic of the', '309255');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (41, 'Costa Rica', '865124');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (42, 'Croatia', '615686');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (43, 'Cuba', '845898');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (44, 'Cyprus', '215604');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (45, 'Czech Republic', '257827');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (46, 'Denmark', '201626');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (47, 'Djibouti', '489648');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (48, 'Dominica', '759420');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (49, 'Dominican Republic', '174171');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (50, 'East Timor (Timor Timur)', '643325');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (51, 'Ecuador', '941897');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (52, 'Egypt', '417095');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (53, 'El Salvador', '291374');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (54, 'Equatorial Guinea', '509455');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (55, 'Eritrea', '879340');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (56, 'Estonia', '133847');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (57, 'Ethiopia', '798479');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (58, 'Fiji', '529182');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (59, 'Finland', '274970');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (60, 'France', '422792');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (61, 'Gabon', '588231');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (62, 'Gambia, The', '135376');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (63, 'Georgia', '398080');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (64, 'Germany', '500751');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (65, 'Ghana', '713874');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (66, 'Greece', '921405');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (67, 'Grenada', '357465');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (68, 'Guatemala', '880843');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (69, 'Guinea', '932350');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (70, 'Guinea-Bissau', '591739');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (71, 'Guyana', '558219');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (72, 'Haiti', '779886');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (73, 'Honduras', '568504');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (74, 'Hungary', '739746');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (75, 'Iceland', '973334');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (76, 'India', '710999');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (77, 'Indonesia', '243480');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (78, 'Iran', '798294');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (79, 'Iraq', '279506');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (80, 'Ireland', '755201');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (81, 'Israel', '146321');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (82, 'Italy', '632354');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (83, 'Jamaica', '178127');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (84, 'Japan', '561410');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (85, 'Jordan', '898170');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (86, 'Kazakhstan', '538993');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (87, 'Kenya', '210092');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (88, 'Kiribati', '210645');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (89, 'Korea, North', '959672');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (90, 'Korea, South', '383179');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (91, 'Kuwait', '348393');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (92, 'Kyrgyzstan', '216026');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (93, 'Laos', '951971');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (94, 'Latvia', '461983');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (95, 'Lebanon', '133926');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (96, 'Lesotho', '658569');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (97, 'Liberia', '199912');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (98, 'Libya', '640371');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (99, 'Liechtenstein', '403882');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (100, 'Lithuania', '322996');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (101, 'Luxembourg', '188835');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (102, 'Macedonia', '351215');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (103, 'Madagascar', '699157');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (104, 'Malawi', '154523');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (105, 'Malaysia', '243586');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (106, 'Maldives', '323681');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (107, 'Mali', '128546');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (108, 'Malta', '666270');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (109, 'Marshall Islands', '985307');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (110, 'Mauritania', '854839');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (111, 'Mauritius', '825538');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (112, 'Mexico', '210856');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (113, 'Micronesia, Federated States of', '874645');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (114, 'Moldova', '945457');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (115, 'Monaco', '170532');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (116, 'Mongolia', '165600');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (117, 'Montenegro', '532742');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (118, 'Morocco', '892605');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (119, 'Mozambique', '297018');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (120, 'Myanmar (Burma)', '611519');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (121, 'Namibia', '148642');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (122, 'Nauru', '561252');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (123, 'Nepal', '313791');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (124, 'Netherlands', '333334');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (125, 'New Zealand', '343488');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (126, 'Nicaragua', '248465');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (127, 'Niger', '625945');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (128, 'Nigeria', '276262');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (129, 'Norway', '442124');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (130, 'Oman', '683413');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (131, 'Pakistan', '342274');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (132, 'Palau', '953422');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (133, 'Panama', '201494');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (134, 'Papua New Guinea', '434765');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (135, 'Paraguay', '732071');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (136, 'Perú', '717434');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (137, 'Philippines', '674841');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (138, 'Poland', '231691');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (139, 'Portugal', '904130');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (140, 'Qatar', '945616');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (141, 'Romania', '754910');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (142, 'Russia', '371259');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (143, 'Rwanda', '399346');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (144, 'Saint Kitts and Nevis', '854786');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (145, 'Saint Lucia', '630745');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (146, 'Saint Vincent and The Grenadines', '718436');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (147, 'Samoa', '919110');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (148, 'San Marino', '958064');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (149, 'Sao Tome and Principe', '923488');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (150, 'Saudi Arabia', '706094');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (151, 'Senegal', '275919');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (152, 'Serbia', '472268');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (153, 'Seychelles', '957985');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (154, 'Sierra Leone', '199200');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (155, 'Singapore', '171165');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (156, 'Slovakia', '774717');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (157, 'Slovenia', '491178');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (158, 'Solomon Islands', '359021');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (159, 'Somalia', '145741');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (160, 'South Africa', '218030');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (161, 'Spain', '576311');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (162, 'Sri Lanka', '186329');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (163, 'Sudan', '172642');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (164, 'Suriname', '179525');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (165, 'Swaziland', '970327');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (166, 'Sweden', '842391');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (167, 'Switzerland', '656960');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (168, 'Syria', '740221');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (169, 'Taiwan', '133873');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (170, 'Tajikistan', '463776');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (171, 'Tanzania', '707491');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (172, 'Thailand', '684837');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (173, 'Togo', '416489');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (174, 'Tonga', '211753');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (175, 'Trinidad and Tobago', '729328');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (176, 'Tunisia', '958591');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (177, 'Turkey', '278820');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (178, 'Turkmenistan', '815490');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (179, 'Tuvalu', '695465');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (180, 'Uganda', '346204');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (181, 'Ukraine', '342011');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (182, 'United Arab Emirates', '843656');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (183, 'United Kingdom', '146796');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (184, 'United States', '657092');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (185, 'Uruguay', '795103');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (186, 'Uzbekistan', '161222');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (187, 'Vanuatu', '784712');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (188, 'Vatican City', '675975');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (189, 'Venezuela', '530843');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (190, 'Vietnam', '793653');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (191, 'Western Sahara', '421711');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (192, 'Yemen', '483872');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (193, 'Zambia', '602473');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (194, 'Zimbabwe', '877520');
INSERT INTO general.pais (id_pais, nombre_pais, cod_cd) VALUES (195, 'Otro', '759183');
