/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   18/07/2016 02:28:23
*/

Ext.define('MyApp.view.GestionarBoletaElectronica.BoletaDetalleWebQueryList' ,{
    extend: 'Ext.grid.Panel',
    alias : 'widget.BoletaDetalleWebQueryList',
    
    glyph:'xf022@FontAwesome',
	header: false,
    store: 'GestionarBoletaElectronica.BoletaDetalleWebQueryStore',

    columns: [
		{
	    	header: "ventas_key",
			flex:1,
			dataIndex: 'ventas_key',
			hidden:true
		}
		,{
			header: "Nro",
			flex:1,
			dataIndex: 'numeroordenitem',
			hidden:false
		}
		,{
			header: "Cod Producto",
			flex:2,
			dataIndex: 'codproducto',
			hidden:false
		}
		,{
			header: "Descripción",
			flex:4,
			dataIndex: 'descripcionitem',
			hidden:false
		}
		,{
			header: "Unidad Medida",
			flex:2,
			dataIndex: 'unidadmedidaitem',
			hidden:false
		}
		,{
			header: "Cantidad",
			flex:1,
			dataIndex: 'cantidaditem',
			hidden:false
		}
		,{
			header: "Precio",
			flex:1,
			dataIndex: 'valorunitarioitem',
			hidden:false
		}
		,{
			header: "montovalorrefunitario",
			flex:1,
			dataIndex: 'montovalorrefunitario',
			hidden:true
		}
		,{
			header: "Precio Venta",
			flex:1,
			dataIndex: 'precioventa',
			hidden:false
		}
		,{
			header: "IGV",
			flex:1,
			dataIndex: 'montoigv',
			hidden:false
		}
		,{
			header: "ISC",
			flex:1,
			dataIndex: 'montoisc',
			hidden:false
		}
		,{
			header: "Valor Venta",
			flex:1,
			dataIndex: 'valorventa',
			hidden:false
		}
	],
	
	initComponent: function() {
		
		this.dockedItems = [
        {
            xtype: 'pagingtoolbar',
            dock:'top',
            store: 'GestionarBoletaElectronica.BoletaDetalleWebQueryStore',
            displayInfo: true
        }];
		
		this.callParent(arguments);
	}
});
