/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The CatalogoItemQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   25/02/2016 19:25:16
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.CatalogoItemQuery;
import pe.com.acme.query.mybatis.model.CatalogoItemQueryCriteria;

public interface CatalogoItemQueryMapper { 
   List<CatalogoItemQuery> getListQueryByCriteria(CatalogoItemQueryCriteria criteria);
   List<CatalogoItemQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<CatalogoItemQuery> getListQueryPaginationByCriteria(CatalogoItemQueryCriteria criteria, RowBounds rowBounds); 
   List<CatalogoItemQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(CatalogoItemQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
