/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The FuncionalidadPorIdSesionQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   28/02/2016 16:46:19
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.FuncionalidadPorIdSesionQuery;
import pe.com.acme.query.mybatis.model.FuncionalidadPorIdSesionQueryCriteria;

public interface FuncionalidadPorIdSesionQueryMapper { 
   List<FuncionalidadPorIdSesionQuery> getListQueryByCriteria(FuncionalidadPorIdSesionQueryCriteria criteria);
   List<FuncionalidadPorIdSesionQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<FuncionalidadPorIdSesionQuery> getListQueryPaginationByCriteria(FuncionalidadPorIdSesionQueryCriteria criteria, RowBounds rowBounds); 
   List<FuncionalidadPorIdSesionQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(FuncionalidadPorIdSesionQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
