/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The RolePorUsuarioAplicacionQueryMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   27/02/2016 22:24:33
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.RolePorUsuarioAplicacionQuery;
import pe.com.acme.query.mybatis.model.RolePorUsuarioAplicacionQueryCriteria;

public interface RolePorUsuarioAplicacionQueryMapper { 
   List<RolePorUsuarioAplicacionQuery> getListQueryByCriteria(RolePorUsuarioAplicacionQueryCriteria criteria);
   List<RolePorUsuarioAplicacionQuery> getListQueryByMap(Map<String, Object> paramMap); 
   List<RolePorUsuarioAplicacionQuery> getListQueryPaginationByCriteria(RolePorUsuarioAplicacionQueryCriteria criteria, RowBounds rowBounds); 
   List<RolePorUsuarioAplicacionQuery> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(RolePorUsuarioAplicacionQueryCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
