/*
* Copyright «©» 2016, INVERSIONES LA IQUEÑA S.A.C. All rights reserved.
*
* This file was generated by MybatisModelGenerator v.3.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [MybatisModelGenerator v.3.0] by JRaffo 
*/

/**
* The UsuarioRolCrudMapper interface conten the methods for run the SQL Query.
*
* @author  Javier Raffo
* @version 1.0
* @since   27/02/2016 13:54:15
*/

package pe.com.acme.query.mybatis.mapper;

import java.util.List; 
import java.util.Map; 
import org.apache.ibatis.session.RowBounds; 
import pe.com.acme.query.mybatis.model.UsuarioRolCrud;
import pe.com.acme.query.mybatis.model.UsuarioRolCrudCriteria;

public interface UsuarioRolCrudMapper { 
   List<UsuarioRolCrud> getListQueryByCriteria(UsuarioRolCrudCriteria criteria);
   List<UsuarioRolCrud> getListQueryByMap(Map<String, Object> paramMap); 
   List<UsuarioRolCrud> getListQueryPaginationByCriteria(UsuarioRolCrudCriteria criteria, RowBounds rowBounds); 
   List<UsuarioRolCrud> getListQueryPaginationByMap(Map<String, Object> paramMap, RowBounds rowBounds); 
   int getCountRowsByCriteria(UsuarioRolCrudCriteria criteria); 
   int getCountRowsByMap(Map<String, Object> paramMap);
} 
