/*
* Copyright «©» 2016, J.R Totem. All rights reserved.
*
* This file was generated by GeneratorCrud v.1.0.
* All changes made in this file will be lost if you recompile the source schema.
*
* [GeneratorCrud v.1.0] by JRaffo 
*/

/**
* @author  Javier Raffo
* @version 1.0
* @since   01/03/2016 21:35:12
*/

package pe.com.acme.inavi.ws.controller;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import pe.com.acme.util.web.ControllerHelper;
import pe.com.acme.util.JsonReturnUtil;
import pe.com.acme.util.ModelWrapper;

import pe.com.acme.inavi.business.service.GestionarClienteNaturalService;
import pe.com.acme.query.mybatis.model.ClienteNaturalQuery;
import pe.com.acme.query.mybatis.model.ClienteNaturalQueryCriteria;

@Controller
@RequestMapping("/GestionarClienteNatural")
public class GestionarClienteNaturalController extends ControllerHelper {

    private static Logger log = Logger.getLogger(GestionarClienteNaturalController.class);

	@Autowired
	private GestionarClienteNaturalService gestionarClienteNaturalService;
	
	@RequestMapping(value="/list")
	public @ResponseBody Map<String,? extends Object> list(HttpServletRequest request) {
		try{
			ClienteNaturalQueryCriteria clienteNaturalQueryCriteria = this.loadCriteria(request, ClienteNaturalQueryCriteria.class);
            List<ClienteNaturalQuery> listClienteNaturalQuery = gestionarClienteNaturalService.list(clienteNaturalQueryCriteria);
			int count = gestionarClienteNaturalService.countRecords(clienteNaturalQueryCriteria);
			return JsonReturnUtil.success(listClienteNaturalQuery,count);
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/create")
	public @ResponseBody Map<String,? extends Object> create(@RequestBody ModelWrapper<ClienteNaturalQuery> modelWrapper) {
		try{
			gestionarClienteNaturalService.create(modelWrapper.getData());
			return JsonReturnUtil.success(modelWrapper.getData().getId_persona());
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/update")
	public @ResponseBody Map<String,? extends Object> update(@RequestBody ModelWrapper<ClienteNaturalQuery> modelWrapper) {
		try{
			gestionarClienteNaturalService.update(modelWrapper.getData());
			return JsonReturnUtil.success();
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
	
	@RequestMapping(value="/destroy")
	public @ResponseBody Map<String,? extends Object> destroy(@RequestBody ModelWrapper<ClienteNaturalQuery> modelWrapper) {
		try{
			gestionarClienteNaturalService.destroy(modelWrapper.getData());
			return JsonReturnUtil.success();
		} catch (Exception e) {
            log.error(e.getMessage(),e);
			return JsonReturnUtil.exception(e.getMessage());
		}
	}
}
